using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace Ceres.SourceGenerator;

internal class BreakStructGeneratorTemplate
{
    private const string StartTemplate =
        """
        /// <auto-generated>
        /// This file is auto-generated by Ceres.SourceGenerator. 
        /// All changes will be discarded.
        /// </auto-generated>
        {USING_NAMESPACES}
        namespace {NAMESPACE}
        {
            [System.Runtime.CompilerServices.CompilerGenerated]
            [System.Serializable]
            [Ceres.Annotations.CeresGroup("Utilities/Structs")]
            [Ceres.Annotations.CeresLabel("Break {STRUCTNAME}")]
            [Ceres.Annotations.CeresMetadata("style = ConstNode", "path = Dependency")]
            [Ceres.Annotations.RequirePort(typeof({STRUCTNAME}))]
            public class FlowNode_Break_{STRUCTNAME} : Ceres.Graph.Flow.ExecutableNode
            {
                [Ceres.Annotations.InputPort, Ceres.Annotations.HideInGraphEditor]
                public Ceres.Graph.CeresPort<{STRUCTNAME}> input;
        """;

    private const string ImplementationTemplate =
        """


                protected override Cysharp.Threading.Tasks.UniTask Execute(Ceres.Graph.Flow.ExecutionContext executionContext)
                {
        """;

    private const string EndTemplate =
        """

                    return Cysharp.Threading.Tasks.UniTask.CompletedTask;
                }
            }
        }
        """;

    public string Namespace;

    public string StructName;

    public List<GeneratorParameterInfo> PublicFields;

    public HashSet<string> Namespaces;

    public string GenerateCode()
    {
        var sb = new StringBuilder();
        var namedCode = StartTemplate
            .Replace("{USING_NAMESPACES}", string.Join("\n", Namespaces))
            .Replace("{NAMESPACE}", Namespace)
            .Replace("{STRUCTNAME}", StructName);
        sb.Append(namedCode);

        // Generate output ports for each public field
        foreach (var field in PublicFields)
        {
            string normalizedName = GetNormalizedName(field.ParameterName);
            string capitalizedLabel = GetCapitalizedName(field.ParameterName);
            sb.Append(
               $"""


                        [Ceres.Annotations.OutputPort, Ceres.Annotations.CeresLabel("{capitalizedLabel}")]
                        public Ceres.Graph.CeresPort<{field.ParameterType}> {normalizedName};
                """);
        }

        sb.Append(ImplementationTemplate);

        // Generate assignment statements
        foreach (var field in PublicFields)
        {
            string normalizedName = GetNormalizedName(field.ParameterName);
            sb.Append(
               $"""
                             
                         {normalizedName}.Value = input.Value.{field.ParameterName};
             """);
        }

        sb.Append(EndTemplate);
        return sb.ToString();
    }

    private static readonly TextInfo TextInfo = new CultureInfo("en-US", false).TextInfo;

    /// <summary>
    /// Normalize field name to camelCase for port field name
    /// </summary>
    private static string GetNormalizedName(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        var sb = new StringBuilder();
        sb.Append(name);
        sb[0] = TextInfo.ToLower(sb[0]);
        return sb.ToString();
    }

    /// <summary>
    /// Capitalize first letter for display label
    /// </summary>
    private static string GetCapitalizedName(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        var sb = new StringBuilder();
        sb.Append(name);
        sb[0] = TextInfo.ToUpper(sb[0]);
        return sb.ToString();
    }
}


