using System.Text;
namespace Ceres.SourceGenerator;

internal class FlowGraphGeneratorTemplate
{
    private const string StartTemplate =
        """
        /// <auto-generated>
        /// This file is auto-generated by Ceres.SourceGenerator. 
        /// All changes will be discarded.
        /// </auto-generated>
        using System;
        using System.Collections.Generic;
        using Ceres.Annotations;
        using Ceres.Graph;
        using Ceres.Graph.Flow;
        using Ceres.Graph.Flow.Annotations;
        using Chris.Serialization;
        using UnityEngine;
        using UnityEngine.Assertions;
        using UObject = UnityEngine.Object;
        namespace {NAMESPACE}
        {
            [System.Runtime.CompilerServices.CompilerGenerated]
            public partial class {CLASSNAME}: {INTERFACE}
            {
        """;

    private const string ImplementationNonRuntimeTemplate =
        """
        
                [SerializeField]
                private FlowGraphData graphData;
                
                public UObject Object => this;
        
                public virtual FlowGraph GetFlowGraph()
                {
                    return graphData.CreateFlowGraphInstance();
                }

                FlowGraphData IFlowGraphContainer.GetFlowGraphData()
                {
                    return graphData;
                }
        
                public virtual void SetGraphData(CeresGraphData graph)
                {
                    graphData = (FlowGraphData)graph;
                }
        
                /// <summary>
                /// Get persistent <see cref="FlowGraphData"/>
                /// </summary>
                /// <returns></returns>
                protected FlowGraphData GetGraphData()
                {
                    return graphData;
                }
            }
        }
        """;
    private const string ImplementationRuntimeTemplate =
        """
        
                [NonSerialized]
                private FlowGraph _graph;

                [NonSerialized]
                private IFlowExecutableProgram _program;
                
                [SerializeField]
                private FlowGraphData graphData;

                [SerializeField]
                [HideInInspector]
                private FlowGeneratedProgramInfo generatedRuntimeInfo = new();
                
                public UObject Object => this;

                FlowGeneratedProgramInfo IFlowGeneratedRuntimeContainer.GeneratedRuntimeInfo => generatedRuntimeInfo;

                public IFlowExecutableProgram Program
                {
                    get
                    {
                        return _program ??= FlowGeneratedRuntimeUtility.CreateExecutableProgram(this, generatedRuntimeInfo);
                    }
                }
        
                public FlowGraph Graph
                {
                    get
                    {
                        if (_graph == null)
                        {
                            _graph = GetFlowGraph();
                            using var context = FlowGraphCompilationContext.GetPooled();
                            using var compiler = CeresGraphCompiler.GetPooled(_graph, context);
                            _graph.Compile(compiler);
                        }
        
                        return _graph;
                    }
                }
        
                /// <summary>
                /// Release graph instance safely
                /// </summary>
                /// <returns></returns>
                protected void ReleaseGraph()
                {
                    if (!ReferenceEquals(_program, _graph))
                    {
                        _program?.Dispose();
                    }
                    _program = null;
                    _graph?.Dispose();
                    _graph = null;
                }
        
                public virtual FlowGraph GetFlowGraph()
                {
                    return graphData.CreateFlowGraphInstance();
                }

                FlowGraphData IFlowGraphContainer.GetFlowGraphData()
                {
                    return graphData;
                }
        
                public virtual void SetGraphData(CeresGraphData graph)
                {
                    graphData = (FlowGraphData)graph;
                }
        
                /// <summary>
                /// Get persistent <see cref="FlowGraphData"/>
                /// </summary>
                /// <returns></returns>
                protected FlowGraphData GetGraphData()
                {
                    return graphData;
                }
            }
        }
        """;

    private const string NonImplementationRuntimeTemplate =
        """
        
                [NonSerialized]
                private FlowGraph _graph;

                [NonSerialized]
                private IFlowExecutableProgram _program;

                public IFlowExecutableProgram Program
                {
                    get
                    {
                        return _program ??= CreateRuntimeProgramInstance();
                    }
                }
        
                public FlowGraph Graph
                {
                    get
                    {
                        if (_graph == null)
                        {
                            _graph = GetFlowGraph();
                            using var context = FlowGraphCompilationContext.GetPooled();
                            using var compiler = CeresGraphCompiler.GetPooled(_graph, context);
                            _graph.Compile(compiler);
                        }
        
                        return _graph;
                    }
                }
        
                /// <summary>
                /// Release graph instance safely
                /// </summary>
                /// <returns></returns>
                protected void ReleaseGraph()
                {
                    if (!ReferenceEquals(_program, _graph))
                    {
                        _program?.Dispose();
                    }
                    _program = null;
                    _graph?.Dispose();
                    _graph = null;
                }

                private IFlowExecutableProgram CreateRuntimeProgramInstance()
                {
                    if (this is IFlowGeneratedRuntimeContainer generatedContainer)
                    {
                        return FlowGeneratedRuntimeUtility.CreateExecutableProgram(generatedContainer,
                            generatedContainer.GeneratedRuntimeInfo);
                    }

                    return FlowGeneratedRuntimeUtility.CreateCompiledGraphProgram(GetFlowGraph());
                }
            }
        }
        """;

    private const string ImplementationInterface = "IFlowGraphContainer";

    private const string GeneratedRuntimeContainerInterface = "IFlowGeneratedRuntimeContainer";

    private const string RuntimeInterface = "IFlowGraphRuntime";

    private const string ProgramRuntimeInterface = "IFlowProgramRuntime";

    public string Namespace;

    public string ClassName;

    public bool GenerateImplementation;

    public bool GenerateRuntime;

    public string GenerateCode()
    {
        var sb = new StringBuilder();
        var namedCode = StartTemplate.Replace("{NAMESPACE}", Namespace).Replace("{CLASSNAME}", ClassName);
        if (GenerateImplementation)
        {
            if (GenerateRuntime)
            {
                sb.Append(namedCode.Replace("{INTERFACE}", string.Join(", ", GeneratedRuntimeContainerInterface,
                    RuntimeInterface, ProgramRuntimeInterface)));
                sb.Append(ImplementationRuntimeTemplate);
            }
            else
            {
                sb.Append(namedCode.Replace("{INTERFACE}", ImplementationInterface));
                sb.Append(ImplementationNonRuntimeTemplate);
            }
        }
        else
        {
            if (GenerateRuntime)
            {
                sb.Append(namedCode.Replace("{INTERFACE}", string.Join(", ", RuntimeInterface, ProgramRuntimeInterface)));
                sb.Append(NonImplementationRuntimeTemplate);
            }
            else
            {
                sb.Append(namedCode.Replace("{INTERFACE}", ImplementationInterface));
                sb.Append(
                    """"
                    
                        }
                    }
                    """");
            }
        }
        return sb.ToString();
    }
}
