### YamlMime:ManagedReference
items:
- uid: Ceres.Graph.APIUpdateConfig
  commentId: T:Ceres.Graph.APIUpdateConfig
  id: APIUpdateConfig
  parent: Ceres.Graph
  children:
  - Ceres.Graph.APIUpdateConfig.#ctor
  - Ceres.Graph.APIUpdateConfig.AutoScope
  - Ceres.Graph.APIUpdateConfig.Current
  - Ceres.Graph.APIUpdateConfig.RedirectManagedReference(Ceres.ManagedReferenceType)
  - Ceres.Graph.APIUpdateConfig.RedirectNode(Ceres.ManagedReferenceType@)
  - Ceres.Graph.APIUpdateConfig.RedirectSerializedType(System.String)
  - Ceres.Graph.APIUpdateConfig.RedirectVariable(Ceres.ManagedReferenceType@)
  langs:
  - csharp
  - vb
  name: APIUpdateConfig
  nameWithType: APIUpdateConfig
  fullName: Ceres.Graph.APIUpdateConfig
  type: Class
  assemblies:
  - Ceres.Graph
  namespace: Ceres.Graph
  syntax:
    content: 'public class APIUpdateConfig : ScriptableObject'
    content.vb: Public Class APIUpdateConfig Inherits ScriptableObject
  inheritance:
  - System.Object
- uid: Ceres.Graph.APIUpdateConfig.RedirectNode(Ceres.ManagedReferenceType@)
  commentId: M:Ceres.Graph.APIUpdateConfig.RedirectNode(Ceres.ManagedReferenceType@)
  id: RedirectNode(Ceres.ManagedReferenceType@)
  parent: Ceres.Graph.APIUpdateConfig
  langs:
  - csharp
  - vb
  name: RedirectNode(in ManagedReferenceType)
  nameWithType: APIUpdateConfig.RedirectNode(in ManagedReferenceType)
  fullName: Ceres.Graph.APIUpdateConfig.RedirectNode(in Ceres.ManagedReferenceType)
  type: Method
  assemblies:
  - Ceres.Graph
  namespace: Ceres.Graph
  syntax:
    content: public Type RedirectNode(in ManagedReferenceType nodeType)
    parameters:
    - id: nodeType
      type: Ceres.ManagedReferenceType
    return:
      type: System.Type
    content.vb: Public Function RedirectNode(nodeType As ManagedReferenceType) As Type
  overload: Ceres.Graph.APIUpdateConfig.RedirectNode*
  nameWithType.vb: APIUpdateConfig.RedirectNode(ManagedReferenceType)
  fullName.vb: Ceres.Graph.APIUpdateConfig.RedirectNode(Ceres.ManagedReferenceType)
  name.vb: RedirectNode(ManagedReferenceType)
- uid: Ceres.Graph.APIUpdateConfig.RedirectVariable(Ceres.ManagedReferenceType@)
  commentId: M:Ceres.Graph.APIUpdateConfig.RedirectVariable(Ceres.ManagedReferenceType@)
  id: RedirectVariable(Ceres.ManagedReferenceType@)
  parent: Ceres.Graph.APIUpdateConfig
  langs:
  - csharp
  - vb
  name: RedirectVariable(in ManagedReferenceType)
  nameWithType: APIUpdateConfig.RedirectVariable(in ManagedReferenceType)
  fullName: Ceres.Graph.APIUpdateConfig.RedirectVariable(in Ceres.ManagedReferenceType)
  type: Method
  assemblies:
  - Ceres.Graph
  namespace: Ceres.Graph
  syntax:
    content: public Type RedirectVariable(in ManagedReferenceType variableType)
    parameters:
    - id: variableType
      type: Ceres.ManagedReferenceType
    return:
      type: System.Type
    content.vb: Public Function RedirectVariable(variableType As ManagedReferenceType) As Type
  overload: Ceres.Graph.APIUpdateConfig.RedirectVariable*
  nameWithType.vb: APIUpdateConfig.RedirectVariable(ManagedReferenceType)
  fullName.vb: Ceres.Graph.APIUpdateConfig.RedirectVariable(Ceres.ManagedReferenceType)
  name.vb: RedirectVariable(ManagedReferenceType)
- uid: Ceres.Graph.APIUpdateConfig.RedirectManagedReference(Ceres.ManagedReferenceType)
  commentId: M:Ceres.Graph.APIUpdateConfig.RedirectManagedReference(Ceres.ManagedReferenceType)
  id: RedirectManagedReference(Ceres.ManagedReferenceType)
  parent: Ceres.Graph.APIUpdateConfig
  langs:
  - csharp
  - vb
  name: RedirectManagedReference(ManagedReferenceType)
  nameWithType: APIUpdateConfig.RedirectManagedReference(ManagedReferenceType)
  fullName: Ceres.Graph.APIUpdateConfig.RedirectManagedReference(Ceres.ManagedReferenceType)
  type: Method
  assemblies:
  - Ceres.Graph
  namespace: Ceres.Graph
  syntax:
    content: public Type RedirectManagedReference(ManagedReferenceType managedReferenceType)
    parameters:
    - id: managedReferenceType
      type: Ceres.ManagedReferenceType
    return:
      type: System.Type
    content.vb: Public Function RedirectManagedReference(managedReferenceType As ManagedReferenceType) As Type
  overload: Ceres.Graph.APIUpdateConfig.RedirectManagedReference*
- uid: Ceres.Graph.APIUpdateConfig.RedirectSerializedType(System.String)
  commentId: M:Ceres.Graph.APIUpdateConfig.RedirectSerializedType(System.String)
  id: RedirectSerializedType(System.String)
  parent: Ceres.Graph.APIUpdateConfig
  langs:
  - csharp
  - vb
  name: RedirectSerializedType(string)
  nameWithType: APIUpdateConfig.RedirectSerializedType(string)
  fullName: Ceres.Graph.APIUpdateConfig.RedirectSerializedType(string)
  type: Method
  assemblies:
  - Ceres.Graph
  namespace: Ceres.Graph
  syntax:
    content: public Type RedirectSerializedType(string serializedType)
    parameters:
    - id: serializedType
      type: System.String
    return:
      type: System.Type
    content.vb: Public Function RedirectSerializedType(serializedType As String) As Type
  overload: Ceres.Graph.APIUpdateConfig.RedirectSerializedType*
  nameWithType.vb: APIUpdateConfig.RedirectSerializedType(String)
  fullName.vb: Ceres.Graph.APIUpdateConfig.RedirectSerializedType(String)
  name.vb: RedirectSerializedType(String)
- uid: Ceres.Graph.APIUpdateConfig.AutoScope
  commentId: M:Ceres.Graph.APIUpdateConfig.AutoScope
  id: AutoScope
  parent: Ceres.Graph.APIUpdateConfig
  langs:
  - csharp
  - vb
  name: AutoScope()
  nameWithType: APIUpdateConfig.AutoScope()
  fullName: Ceres.Graph.APIUpdateConfig.AutoScope()
  type: Method
  assemblies:
  - Ceres.Graph
  namespace: Ceres.Graph
  syntax:
    content: public static APIUpdateConfig.ConfigAutoScope AutoScope()
    return:
      type: Ceres.Graph.APIUpdateConfig.ConfigAutoScope
    content.vb: Public Shared Function AutoScope() As APIUpdateConfig.ConfigAutoScope
  overload: Ceres.Graph.APIUpdateConfig.AutoScope*
- uid: Ceres.Graph.APIUpdateConfig.#ctor
  commentId: M:Ceres.Graph.APIUpdateConfig.#ctor
  id: '#ctor'
  parent: Ceres.Graph.APIUpdateConfig
  langs:
  - csharp
  - vb
  name: APIUpdateConfig()
  nameWithType: APIUpdateConfig.APIUpdateConfig()
  fullName: Ceres.Graph.APIUpdateConfig.APIUpdateConfig()
  type: Constructor
  assemblies:
  - Ceres.Graph
  namespace: Ceres.Graph
  syntax:
    content: public APIUpdateConfig()
    content.vb: Public Sub New()
  overload: Ceres.Graph.APIUpdateConfig.#ctor*
  nameWithType.vb: APIUpdateConfig.New()
  fullName.vb: Ceres.Graph.APIUpdateConfig.New()
  name.vb: New()
- uid: Ceres.Graph.APIUpdateConfig.Current
  commentId: P:Ceres.Graph.APIUpdateConfig.Current
  id: Current
  parent: Ceres.Graph.APIUpdateConfig
  langs:
  - csharp
  - vb
  name: Current
  nameWithType: APIUpdateConfig.Current
  fullName: Ceres.Graph.APIUpdateConfig.Current
  type: Property
  assemblies:
  - Ceres.Graph
  namespace: Ceres.Graph
  summary: Current active config, can be null if no valid config
  example: []
  syntax:
    content: public static APIUpdateConfig Current { get; }
    parameters: []
    return:
      type: Ceres.Graph.APIUpdateConfig
    content.vb: Public Shared ReadOnly Property Current As APIUpdateConfig
  overload: Ceres.Graph.APIUpdateConfig.Current*
references:
- uid: Ceres.Graph
  commentId: N:Ceres.Graph
  isExternal: true
  href: Ceres.html
  name: Ceres.Graph
  nameWithType: Ceres.Graph
  fullName: Ceres.Graph
  spec.csharp:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Graph
    name: Graph
    isExternal: true
    href: Ceres.Graph.html
  spec.vb:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Graph
    name: Graph
    isExternal: true
    href: Ceres.Graph.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Ceres.Graph.APIUpdateConfig.RedirectNode*
  commentId: Overload:Ceres.Graph.APIUpdateConfig.RedirectNode
  isExternal: true
  href: Ceres.Graph.APIUpdateConfig.html#Ceres_Graph_APIUpdateConfig_RedirectNode_Ceres_ManagedReferenceType__
  name: RedirectNode
  nameWithType: APIUpdateConfig.RedirectNode
  fullName: Ceres.Graph.APIUpdateConfig.RedirectNode
- uid: Ceres.ManagedReferenceType
  commentId: T:Ceres.ManagedReferenceType
  parent: Ceres
  isExternal: true
  href: Ceres.ManagedReferenceType.html
  name: ManagedReferenceType
  nameWithType: ManagedReferenceType
  fullName: Ceres.ManagedReferenceType
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.type
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: Ceres
  commentId: N:Ceres
  isExternal: true
  href: Ceres.html
  name: Ceres
  nameWithType: Ceres
  fullName: Ceres
- uid: Ceres.Graph.APIUpdateConfig.RedirectVariable*
  commentId: Overload:Ceres.Graph.APIUpdateConfig.RedirectVariable
  isExternal: true
  href: Ceres.Graph.APIUpdateConfig.html#Ceres_Graph_APIUpdateConfig_RedirectVariable_Ceres_ManagedReferenceType__
  name: RedirectVariable
  nameWithType: APIUpdateConfig.RedirectVariable
  fullName: Ceres.Graph.APIUpdateConfig.RedirectVariable
- uid: Ceres.Graph.APIUpdateConfig.RedirectManagedReference*
  commentId: Overload:Ceres.Graph.APIUpdateConfig.RedirectManagedReference
  isExternal: true
  href: Ceres.Graph.APIUpdateConfig.html#Ceres_Graph_APIUpdateConfig_RedirectManagedReference_Ceres_ManagedReferenceType_
  name: RedirectManagedReference
  nameWithType: APIUpdateConfig.RedirectManagedReference
  fullName: Ceres.Graph.APIUpdateConfig.RedirectManagedReference
- uid: Ceres.Graph.APIUpdateConfig.RedirectSerializedType*
  commentId: Overload:Ceres.Graph.APIUpdateConfig.RedirectSerializedType
  isExternal: true
  href: Ceres.Graph.APIUpdateConfig.html#Ceres_Graph_APIUpdateConfig_RedirectSerializedType_System_String_
  name: RedirectSerializedType
  nameWithType: APIUpdateConfig.RedirectSerializedType
  fullName: Ceres.Graph.APIUpdateConfig.RedirectSerializedType
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Ceres.Graph.APIUpdateConfig.AutoScope*
  commentId: Overload:Ceres.Graph.APIUpdateConfig.AutoScope
  isExternal: true
  href: Ceres.Graph.APIUpdateConfig.html#Ceres_Graph_APIUpdateConfig_AutoScope
  name: AutoScope
  nameWithType: APIUpdateConfig.AutoScope
  fullName: Ceres.Graph.APIUpdateConfig.AutoScope
- uid: Ceres.Graph.APIUpdateConfig.ConfigAutoScope
  commentId: T:Ceres.Graph.APIUpdateConfig.ConfigAutoScope
  parent: Ceres.Graph
  isExternal: true
  href: Ceres.Graph.APIUpdateConfig.html
  name: APIUpdateConfig.ConfigAutoScope
  nameWithType: APIUpdateConfig.ConfigAutoScope
  fullName: Ceres.Graph.APIUpdateConfig.ConfigAutoScope
  spec.csharp:
  - uid: Ceres.Graph.APIUpdateConfig
    name: APIUpdateConfig
    isExternal: true
    href: Ceres.Graph.APIUpdateConfig.html
  - name: .
  - uid: Ceres.Graph.APIUpdateConfig.ConfigAutoScope
    name: ConfigAutoScope
    isExternal: true
    href: Ceres.Graph.APIUpdateConfig.ConfigAutoScope.html
  spec.vb:
  - uid: Ceres.Graph.APIUpdateConfig
    name: APIUpdateConfig
    isExternal: true
    href: Ceres.Graph.APIUpdateConfig.html
  - name: .
  - uid: Ceres.Graph.APIUpdateConfig.ConfigAutoScope
    name: ConfigAutoScope
    isExternal: true
    href: Ceres.Graph.APIUpdateConfig.ConfigAutoScope.html
- uid: Ceres.Graph.APIUpdateConfig.#ctor*
  commentId: Overload:Ceres.Graph.APIUpdateConfig.#ctor
  isExternal: true
  href: Ceres.Graph.APIUpdateConfig.html#Ceres_Graph_APIUpdateConfig__ctor
  name: APIUpdateConfig
  nameWithType: APIUpdateConfig.APIUpdateConfig
  fullName: Ceres.Graph.APIUpdateConfig.APIUpdateConfig
  nameWithType.vb: APIUpdateConfig.New
  fullName.vb: Ceres.Graph.APIUpdateConfig.New
  name.vb: New
- uid: Ceres.Graph.APIUpdateConfig.Current*
  commentId: Overload:Ceres.Graph.APIUpdateConfig.Current
  isExternal: true
  href: Ceres.Graph.APIUpdateConfig.html#Ceres_Graph_APIUpdateConfig_Current
  name: Current
  nameWithType: APIUpdateConfig.Current
  fullName: Ceres.Graph.APIUpdateConfig.Current
- uid: Ceres.Graph.APIUpdateConfig
  commentId: T:Ceres.Graph.APIUpdateConfig
  parent: Ceres.Graph
  isExternal: true
  href: Ceres.Graph.APIUpdateConfig.html
  name: APIUpdateConfig
  nameWithType: APIUpdateConfig
  fullName: Ceres.Graph.APIUpdateConfig
