### YamlMime:ManagedReference
items:
- uid: Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode
  commentId: T:Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode
  id: CeresSettings.GraphEditorDisplayMode
  parent: Ceres.Editor.Graph
  children:
  - Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode.Debug
  - Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode.Normal
  langs:
  - csharp
  - vb
  name: CeresSettings.GraphEditorDisplayMode
  nameWithType: CeresSettings.GraphEditorDisplayMode
  fullName: Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode
  type: Enum
  assemblies:
  - Ceres.Graph.Editor
  namespace: Ceres.Editor.Graph
  syntax:
    content: public enum CeresSettings.GraphEditorDisplayMode
    content.vb: Public Enum CeresSettings.GraphEditorDisplayMode
- uid: Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode.Normal
  commentId: F:Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode.Normal
  id: Normal
  parent: Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode
  langs:
  - csharp
  - vb
  name: Normal
  nameWithType: CeresSettings.GraphEditorDisplayMode.Normal
  fullName: Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode.Normal
  type: Field
  assemblies:
  - Ceres.Graph.Editor
  namespace: Ceres.Editor.Graph
  syntax:
    content: Normal = 0
    return:
      type: Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode
- uid: Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode.Debug
  commentId: F:Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode.Debug
  id: Debug
  parent: Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode
  langs:
  - csharp
  - vb
  name: Debug
  nameWithType: CeresSettings.GraphEditorDisplayMode.Debug
  fullName: Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode.Debug
  type: Field
  assemblies:
  - Ceres.Graph.Editor
  namespace: Ceres.Editor.Graph
  syntax:
    content: Debug = 1
    return:
      type: Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode
references:
- uid: Ceres.Editor.Graph
  commentId: N:Ceres.Editor.Graph
  isExternal: true
  href: Ceres.html
  name: Ceres.Editor.Graph
  nameWithType: Ceres.Editor.Graph
  fullName: Ceres.Editor.Graph
  spec.csharp:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Editor
    name: Editor
    isExternal: true
    href: Ceres.Editor.html
  - name: .
  - uid: Ceres.Editor.Graph
    name: Graph
    isExternal: true
    href: Ceres.Editor.Graph.html
  spec.vb:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Editor
    name: Editor
    isExternal: true
    href: Ceres.Editor.html
  - name: .
  - uid: Ceres.Editor.Graph
    name: Graph
    isExternal: true
    href: Ceres.Editor.Graph.html
- uid: Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode
  commentId: T:Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode
  parent: Ceres.Editor.Graph
  isExternal: true
  href: Ceres.Editor.Graph.CeresSettings.html
  name: CeresSettings.GraphEditorDisplayMode
  nameWithType: CeresSettings.GraphEditorDisplayMode
  fullName: Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode
  spec.csharp:
  - uid: Ceres.Editor.Graph.CeresSettings
    name: CeresSettings
    isExternal: true
    href: Ceres.Editor.Graph.CeresSettings.html
  - name: .
  - uid: Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode
    name: GraphEditorDisplayMode
    isExternal: true
    href: Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode.html
  spec.vb:
  - uid: Ceres.Editor.Graph.CeresSettings
    name: CeresSettings
    isExternal: true
    href: Ceres.Editor.Graph.CeresSettings.html
  - name: .
  - uid: Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode
    name: GraphEditorDisplayMode
    isExternal: true
    href: Ceres.Editor.Graph.CeresSettings.GraphEditorDisplayMode.html
