### YamlMime:ManagedReference
items:
- uid: Ceres.Configs.ConfigFileLocation
  commentId: T:Ceres.Configs.ConfigFileLocation
  id: ConfigFileLocation
  parent: Ceres.Configs
  children:
  - Ceres.Configs.ConfigFileLocation.Path
  - Ceres.Configs.ConfigFileLocation.op_Implicit(Ceres.Configs.ConfigFileLocation)~System.String
  - Ceres.Configs.ConfigFileLocation.op_Implicit(System.String)~Ceres.Configs.ConfigFileLocation
  langs:
  - csharp
  - vb
  name: ConfigFileLocation
  nameWithType: ConfigFileLocation
  fullName: Ceres.Configs.ConfigFileLocation
  type: Struct
  assemblies:
  - Ceres
  namespace: Ceres.Configs
  summary: Identifier for specific <xref href="Ceres.Configs.ConfigFile" data-throw-if-not-resolved="false"></xref>
  example: []
  syntax:
    content: public readonly struct ConfigFileLocation
    content.vb: Public Structure ConfigFileLocation
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.GetType
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: Ceres.Configs.ConfigFileLocation.Path
  commentId: F:Ceres.Configs.ConfigFileLocation.Path
  id: Path
  parent: Ceres.Configs.ConfigFileLocation
  langs:
  - csharp
  - vb
  name: Path
  nameWithType: ConfigFileLocation.Path
  fullName: Ceres.Configs.ConfigFileLocation.Path
  type: Field
  assemblies:
  - Ceres
  namespace: Ceres.Configs
  syntax:
    content: public readonly string Path
    return:
      type: System.String
    content.vb: Public ReadOnly Path As String
- uid: Ceres.Configs.ConfigFileLocation.op_Implicit(System.String)~Ceres.Configs.ConfigFileLocation
  commentId: M:Ceres.Configs.ConfigFileLocation.op_Implicit(System.String)~Ceres.Configs.ConfigFileLocation
  id: op_Implicit(System.String)~Ceres.Configs.ConfigFileLocation
  parent: Ceres.Configs.ConfigFileLocation
  langs:
  - csharp
  - vb
  name: implicit operator ConfigFileLocation(string)
  nameWithType: ConfigFileLocation.implicit operator ConfigFileLocation(string)
  fullName: Ceres.Configs.ConfigFileLocation.implicit operator Ceres.Configs.ConfigFileLocation(string)
  type: Operator
  assemblies:
  - Ceres
  namespace: Ceres.Configs
  syntax:
    content: public static implicit operator ConfigFileLocation(string path)
    parameters:
    - id: path
      type: System.String
    return:
      type: Ceres.Configs.ConfigFileLocation
    content.vb: Public Shared Widening Operator CType(path As String) As ConfigFileLocation
  overload: Ceres.Configs.ConfigFileLocation.op_Implicit*
  nameWithType.vb: ConfigFileLocation.CType(String)
  fullName.vb: Ceres.Configs.ConfigFileLocation.CType(String)
  name.vb: CType(String)
- uid: Ceres.Configs.ConfigFileLocation.op_Implicit(Ceres.Configs.ConfigFileLocation)~System.String
  commentId: M:Ceres.Configs.ConfigFileLocation.op_Implicit(Ceres.Configs.ConfigFileLocation)~System.String
  id: op_Implicit(Ceres.Configs.ConfigFileLocation)~System.String
  parent: Ceres.Configs.ConfigFileLocation
  langs:
  - csharp
  - vb
  name: implicit operator string(ConfigFileLocation)
  nameWithType: ConfigFileLocation.implicit operator string(ConfigFileLocation)
  fullName: Ceres.Configs.ConfigFileLocation.implicit operator string(Ceres.Configs.ConfigFileLocation)
  type: Operator
  assemblies:
  - Ceres
  namespace: Ceres.Configs
  syntax:
    content: public static implicit operator string(ConfigFileLocation location)
    parameters:
    - id: location
      type: Ceres.Configs.ConfigFileLocation
    return:
      type: System.String
    content.vb: Public Shared Widening Operator CType(location As ConfigFileLocation) As String
  overload: Ceres.Configs.ConfigFileLocation.op_Implicit*
  nameWithType.vb: ConfigFileLocation.CType(ConfigFileLocation)
  fullName.vb: Ceres.Configs.ConfigFileLocation.CType(Ceres.Configs.ConfigFileLocation)
  name.vb: CType(ConfigFileLocation)
references:
- uid: Ceres.Configs.ConfigFile
  commentId: T:Ceres.Configs.ConfigFile
  isExternal: true
  name: ConfigFile
  nameWithType: ConfigFile
  fullName: Ceres.Configs.ConfigFile
- uid: Ceres.Configs
  commentId: N:Ceres.Configs
  isExternal: true
  href: Ceres.html
  name: Ceres.Configs
  nameWithType: Ceres.Configs
  fullName: Ceres.Configs
  spec.csharp:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Configs
    name: Configs
    isExternal: true
    href: Ceres.Configs.html
  spec.vb:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Configs
    name: Configs
    isExternal: true
    href: Ceres.Configs.html
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Ceres.Configs.ConfigFileLocation.op_Implicit*
  commentId: Overload:Ceres.Configs.ConfigFileLocation.op_Implicit
  name: implicit operator
  nameWithType: ConfigFileLocation.implicit operator
  fullName: Ceres.Configs.ConfigFileLocation.implicit operator
  nameWithType.vb: ConfigFileLocation.CType
  fullName.vb: Ceres.Configs.ConfigFileLocation.CType
  name.vb: CType
  spec.csharp:
  - name: implicit
  - name: " "
  - name: operator
- uid: Ceres.Configs.ConfigFileLocation
  commentId: T:Ceres.Configs.ConfigFileLocation
  parent: Ceres.Configs
  isExternal: true
  href: Ceres.Configs.ConfigFileLocation.html
  name: ConfigFileLocation
  nameWithType: ConfigFileLocation
  fullName: Ceres.Configs.ConfigFileLocation
