### YamlMime:ManagedReference
items:
- uid: Ceres.Gameplay.AI.EQS.EnvironmentQuery
  commentId: T:Ceres.Gameplay.AI.EQS.EnvironmentQuery
  id: EnvironmentQuery
  parent: Ceres.Gameplay.AI.EQS
  children:
  - Ceres.Gameplay.AI.EQS.EnvironmentQuery.OverlapFieldView(System.Collections.Generic.List{Ceres.Gameplay.Actor},UnityEngine.Vector3,UnityEngine.Vector3,System.Single,System.Single,UnityEngine.LayerMask,Ceres.Gameplay.Actor)
  langs:
  - csharp
  - vb
  name: EnvironmentQuery
  nameWithType: EnvironmentQuery
  fullName: Ceres.Gameplay.AI.EQS.EnvironmentQuery
  type: Class
  assemblies:
  - Ceres.Gameplay
  namespace: Ceres.Gameplay.AI.EQS
  summary: API for query actors
  example: []
  syntax:
    content: public static class EnvironmentQuery
    content.vb: Public Module EnvironmentQuery
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: Ceres.Gameplay.AI.EQS.EnvironmentQuery.OverlapFieldView(System.Collections.Generic.List{Ceres.Gameplay.Actor},UnityEngine.Vector3,UnityEngine.Vector3,System.Single,System.Single,UnityEngine.LayerMask,Ceres.Gameplay.Actor)
  commentId: M:Ceres.Gameplay.AI.EQS.EnvironmentQuery.OverlapFieldView(System.Collections.Generic.List{Ceres.Gameplay.Actor},UnityEngine.Vector3,UnityEngine.Vector3,System.Single,System.Single,UnityEngine.LayerMask,Ceres.Gameplay.Actor)
  id: OverlapFieldView(System.Collections.Generic.List{Ceres.Gameplay.Actor},UnityEngine.Vector3,UnityEngine.Vector3,System.Single,System.Single,UnityEngine.LayerMask,Ceres.Gameplay.Actor)
  parent: Ceres.Gameplay.AI.EQS.EnvironmentQuery
  langs:
  - csharp
  - vb
  name: OverlapFieldView(List<Actor>, Vector3, Vector3, float, float, LayerMask, Actor)
  nameWithType: EnvironmentQuery.OverlapFieldView(List<Actor>, Vector3, Vector3, float, float, LayerMask, Actor)
  fullName: Ceres.Gameplay.AI.EQS.EnvironmentQuery.OverlapFieldView(System.Collections.Generic.List<Ceres.Gameplay.Actor>, UnityEngine.Vector3, UnityEngine.Vector3, float, float, UnityEngine.LayerMask, Ceres.Gameplay.Actor)
  type: Method
  assemblies:
  - Ceres.Gameplay
  namespace: Ceres.Gameplay.AI.EQS
  summary: Query actors overlap in field of view immediately
  example: []
  syntax:
    content: public static void OverlapFieldView(List<Actor> actors, Vector3 position, Vector3 forward, float radius, float angle, LayerMask targetMask, Actor ignoredActor = null)
    parameters:
    - id: actors
      type: System.Collections.Generic.List{Ceres.Gameplay.Actor}
      description: ''
    - id: position
      type: UnityEngine.Vector3
      description: ''
    - id: forward
      type: UnityEngine.Vector3
      description: ''
    - id: radius
      type: System.Single
      description: ''
    - id: angle
      type: System.Single
      description: ''
    - id: targetMask
      type: UnityEngine.LayerMask
      description: ''
    - id: ignoredActor
      type: Ceres.Gameplay.Actor
      description: ''
    content.vb: Public Shared Sub OverlapFieldView(actors As List(Of Actor), position As Vector3, forward As Vector3, radius As Single, angle As Single, targetMask As LayerMask, ignoredActor As Actor = Nothing)
  overload: Ceres.Gameplay.AI.EQS.EnvironmentQuery.OverlapFieldView*
  nameWithType.vb: EnvironmentQuery.OverlapFieldView(List(Of Actor), Vector3, Vector3, Single, Single, LayerMask, Actor)
  fullName.vb: Ceres.Gameplay.AI.EQS.EnvironmentQuery.OverlapFieldView(System.Collections.Generic.List(Of Ceres.Gameplay.Actor), UnityEngine.Vector3, UnityEngine.Vector3, Single, Single, UnityEngine.LayerMask, Ceres.Gameplay.Actor)
  name.vb: OverlapFieldView(List(Of Actor), Vector3, Vector3, Single, Single, LayerMask, Actor)
references:
- uid: Ceres.Gameplay.AI.EQS
  commentId: N:Ceres.Gameplay.AI.EQS
  isExternal: true
  href: Ceres.html
  name: Ceres.Gameplay.AI.EQS
  nameWithType: Ceres.Gameplay.AI.EQS
  fullName: Ceres.Gameplay.AI.EQS
  spec.csharp:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Gameplay
    name: Gameplay
    isExternal: true
    href: Ceres.Gameplay.html
  - name: .
  - uid: Ceres.Gameplay.AI
    name: AI
    isExternal: true
    href: Ceres.Gameplay.AI.html
  - name: .
  - uid: Ceres.Gameplay.AI.EQS
    name: EQS
    isExternal: true
    href: Ceres.Gameplay.AI.EQS.html
  spec.vb:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Gameplay
    name: Gameplay
    isExternal: true
    href: Ceres.Gameplay.html
  - name: .
  - uid: Ceres.Gameplay.AI
    name: AI
    isExternal: true
    href: Ceres.Gameplay.AI.html
  - name: .
  - uid: Ceres.Gameplay.AI.EQS
    name: EQS
    isExternal: true
    href: Ceres.Gameplay.AI.EQS.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Ceres.Gameplay.AI.EQS.EnvironmentQuery.OverlapFieldView*
  commentId: Overload:Ceres.Gameplay.AI.EQS.EnvironmentQuery.OverlapFieldView
  isExternal: true
  href: Ceres.Gameplay.AI.EQS.EnvironmentQuery.html#Ceres_Gameplay_AI_EQS_EnvironmentQuery_OverlapFieldView_System_Collections_Generic_List_Ceres_Gameplay_Actor__UnityEngine_Vector3_UnityEngine_Vector3_System_Single_System_Single_UnityEngine_LayerMask_Ceres_Gameplay_Actor_
  name: OverlapFieldView
  nameWithType: EnvironmentQuery.OverlapFieldView
  fullName: Ceres.Gameplay.AI.EQS.EnvironmentQuery.OverlapFieldView
- uid: System.Collections.Generic.List{Ceres.Gameplay.Actor}
  commentId: T:System.Collections.Generic.List{Ceres.Gameplay.Actor}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<Actor>
  nameWithType: List<Actor>
  fullName: System.Collections.Generic.List<Ceres.Gameplay.Actor>
  nameWithType.vb: List(Of Actor)
  fullName.vb: System.Collections.Generic.List(Of Ceres.Gameplay.Actor)
  name.vb: List(Of Actor)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Ceres.Gameplay.Actor
    name: Actor
    isExternal: true
    href: Ceres.Gameplay.Actor.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Ceres.Gameplay.Actor
    name: Actor
    isExternal: true
    href: Ceres.Gameplay.Actor.html
  - name: )
- uid: UnityEngine.Vector3
  isExternal: true
  name: Vector3
  nameWithType: Vector3
  fullName: UnityEngine.Vector3
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: UnityEngine.LayerMask
  isExternal: true
  name: LayerMask
  nameWithType: LayerMask
  fullName: UnityEngine.LayerMask
- uid: Ceres.Gameplay.Actor
  commentId: T:Ceres.Gameplay.Actor
  parent: Ceres.Gameplay
  isExternal: true
  href: Ceres.Gameplay.Actor.html
  name: Actor
  nameWithType: Actor
  fullName: Ceres.Gameplay.Actor
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Ceres.Gameplay
  commentId: N:Ceres.Gameplay
  isExternal: true
  href: Ceres.html
  name: Ceres.Gameplay
  nameWithType: Ceres.Gameplay
  fullName: Ceres.Gameplay
  spec.csharp:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Gameplay
    name: Gameplay
    isExternal: true
    href: Ceres.Gameplay.html
  spec.vb:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Gameplay
    name: Gameplay
    isExternal: true
    href: Ceres.Gameplay.html
