### YamlMime:ManagedReference
items:
- uid: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor
  commentId: T:Ceres.Gameplay.Mod.Editor.ModExportConfigEditor
  id: ModExportConfigEditor
  parent: Ceres.Gameplay.Mod.Editor
  children:
  - Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.#ctor
  - Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.OnInspectorGUI
  - Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.SetEditMode(System.Boolean)
  langs:
  - csharp
  - vb
  name: ModExportConfigEditor
  nameWithType: ModExportConfigEditor
  fullName: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor
  type: Class
  assemblies:
  - Ceres.Gameplay.Editor
  namespace: Ceres.Gameplay.Mod.Editor
  syntax:
    content: 'public class ModExportConfigEditor : Editor'
    content.vb: Public Class ModExportConfigEditor Inherits Editor
  inheritance:
  - System.Object
- uid: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.SetEditMode(System.Boolean)
  commentId: M:Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.SetEditMode(System.Boolean)
  id: SetEditMode(System.Boolean)
  parent: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor
  langs:
  - csharp
  - vb
  name: SetEditMode(bool)
  nameWithType: ModExportConfigEditor.SetEditMode(bool)
  fullName: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.SetEditMode(bool)
  type: Method
  assemblies:
  - Ceres.Gameplay.Editor
  namespace: Ceres.Gameplay.Mod.Editor
  summary: Set config to edit mode for ModExportWindow
  example: []
  syntax:
    content: public void SetEditMode(bool isEditMode)
    parameters:
    - id: isEditMode
      type: System.Boolean
      description: ''
    content.vb: Public Sub SetEditMode(isEditMode As Boolean)
  overload: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.SetEditMode*
  nameWithType.vb: ModExportConfigEditor.SetEditMode(Boolean)
  fullName.vb: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.SetEditMode(Boolean)
  name.vb: SetEditMode(Boolean)
- uid: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.OnInspectorGUI
  commentId: M:Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.OnInspectorGUI
  id: OnInspectorGUI
  parent: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor
  langs:
  - csharp
  - vb
  name: OnInspectorGUI()
  nameWithType: ModExportConfigEditor.OnInspectorGUI()
  fullName: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.OnInspectorGUI()
  type: Method
  assemblies:
  - Ceres.Gameplay.Editor
  namespace: Ceres.Gameplay.Mod.Editor
  example: []
  syntax:
    content: public override void OnInspectorGUI()
    content.vb: Public Overrides Sub OnInspectorGUI()
  overload: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.OnInspectorGUI*
- uid: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.#ctor
  commentId: M:Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.#ctor
  id: '#ctor'
  parent: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor
  langs:
  - csharp
  - vb
  name: ModExportConfigEditor()
  nameWithType: ModExportConfigEditor.ModExportConfigEditor()
  fullName: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.ModExportConfigEditor()
  type: Constructor
  assemblies:
  - Ceres.Gameplay.Editor
  namespace: Ceres.Gameplay.Mod.Editor
  syntax:
    content: public ModExportConfigEditor()
    content.vb: Public Sub New()
  overload: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.#ctor*
  nameWithType.vb: ModExportConfigEditor.New()
  fullName.vb: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.New()
  name.vb: New()
references:
- uid: Ceres.Gameplay.Mod.Editor
  commentId: N:Ceres.Gameplay.Mod.Editor
  isExternal: true
  href: Ceres.html
  name: Ceres.Gameplay.Mod.Editor
  nameWithType: Ceres.Gameplay.Mod.Editor
  fullName: Ceres.Gameplay.Mod.Editor
  spec.csharp:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Gameplay
    name: Gameplay
    isExternal: true
    href: Ceres.Gameplay.html
  - name: .
  - uid: Ceres.Gameplay.Mod
    name: Mod
    isExternal: true
    href: Ceres.Gameplay.Mod.html
  - name: .
  - uid: Ceres.Gameplay.Mod.Editor
    name: Editor
    isExternal: true
    href: Ceres.Gameplay.Mod.Editor.html
  spec.vb:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Gameplay
    name: Gameplay
    isExternal: true
    href: Ceres.Gameplay.html
  - name: .
  - uid: Ceres.Gameplay.Mod
    name: Mod
    isExternal: true
    href: Ceres.Gameplay.Mod.html
  - name: .
  - uid: Ceres.Gameplay.Mod.Editor
    name: Editor
    isExternal: true
    href: Ceres.Gameplay.Mod.Editor.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.SetEditMode*
  commentId: Overload:Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.SetEditMode
  isExternal: true
  href: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.html#Ceres_Gameplay_Mod_Editor_ModExportConfigEditor_SetEditMode_System_Boolean_
  name: SetEditMode
  nameWithType: ModExportConfigEditor.SetEditMode
  fullName: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.SetEditMode
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.OnInspectorGUI*
  commentId: Overload:Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.OnInspectorGUI
  isExternal: true
  href: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.html#Ceres_Gameplay_Mod_Editor_ModExportConfigEditor_OnInspectorGUI
  name: OnInspectorGUI
  nameWithType: ModExportConfigEditor.OnInspectorGUI
  fullName: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.OnInspectorGUI
- uid: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.#ctor*
  commentId: Overload:Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.#ctor
  isExternal: true
  href: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.html#Ceres_Gameplay_Mod_Editor_ModExportConfigEditor__ctor
  name: ModExportConfigEditor
  nameWithType: ModExportConfigEditor.ModExportConfigEditor
  fullName: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.ModExportConfigEditor
  nameWithType.vb: ModExportConfigEditor.New
  fullName.vb: Ceres.Gameplay.Mod.Editor.ModExportConfigEditor.New
  name.vb: New
