### YamlMime:ManagedReference
items:
- uid: Ceres.Editor.Graph.APIUpdateConfigEditor
  commentId: T:Ceres.Editor.Graph.APIUpdateConfigEditor
  id: APIUpdateConfigEditor
  parent: Ceres.Editor.Graph
  children:
  - Ceres.Editor.Graph.APIUpdateConfigEditor.#ctor
  - Ceres.Editor.Graph.APIUpdateConfigEditor.OnInspectorGUI
  langs:
  - csharp
  - vb
  name: APIUpdateConfigEditor
  nameWithType: APIUpdateConfigEditor
  fullName: Ceres.Editor.Graph.APIUpdateConfigEditor
  type: Class
  assemblies:
  - Ceres.Graph.Editor
  namespace: Ceres.Editor.Graph
  syntax:
    content: 'public class APIUpdateConfigEditor : Editor'
    content.vb: Public Class APIUpdateConfigEditor Inherits Editor
  inheritance:
  - System.Object
- uid: Ceres.Editor.Graph.APIUpdateConfigEditor.OnInspectorGUI
  commentId: M:Ceres.Editor.Graph.APIUpdateConfigEditor.OnInspectorGUI
  id: OnInspectorGUI
  parent: Ceres.Editor.Graph.APIUpdateConfigEditor
  langs:
  - csharp
  - vb
  name: OnInspectorGUI()
  nameWithType: APIUpdateConfigEditor.OnInspectorGUI()
  fullName: Ceres.Editor.Graph.APIUpdateConfigEditor.OnInspectorGUI()
  type: Method
  assemblies:
  - Ceres.Graph.Editor
  namespace: Ceres.Editor.Graph
  example: []
  syntax:
    content: public override void OnInspectorGUI()
    content.vb: Public Overrides Sub OnInspectorGUI()
  overload: Ceres.Editor.Graph.APIUpdateConfigEditor.OnInspectorGUI*
- uid: Ceres.Editor.Graph.APIUpdateConfigEditor.#ctor
  commentId: M:Ceres.Editor.Graph.APIUpdateConfigEditor.#ctor
  id: '#ctor'
  parent: Ceres.Editor.Graph.APIUpdateConfigEditor
  langs:
  - csharp
  - vb
  name: APIUpdateConfigEditor()
  nameWithType: APIUpdateConfigEditor.APIUpdateConfigEditor()
  fullName: Ceres.Editor.Graph.APIUpdateConfigEditor.APIUpdateConfigEditor()
  type: Constructor
  assemblies:
  - Ceres.Graph.Editor
  namespace: Ceres.Editor.Graph
  syntax:
    content: public APIUpdateConfigEditor()
    content.vb: Public Sub New()
  overload: Ceres.Editor.Graph.APIUpdateConfigEditor.#ctor*
  nameWithType.vb: APIUpdateConfigEditor.New()
  fullName.vb: Ceres.Editor.Graph.APIUpdateConfigEditor.New()
  name.vb: New()
references:
- uid: Ceres.Editor.Graph
  commentId: N:Ceres.Editor.Graph
  isExternal: true
  href: Ceres.html
  name: Ceres.Editor.Graph
  nameWithType: Ceres.Editor.Graph
  fullName: Ceres.Editor.Graph
  spec.csharp:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Editor
    name: Editor
    isExternal: true
    href: Ceres.Editor.html
  - name: .
  - uid: Ceres.Editor.Graph
    name: Graph
    isExternal: true
    href: Ceres.Editor.Graph.html
  spec.vb:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Editor
    name: Editor
    isExternal: true
    href: Ceres.Editor.html
  - name: .
  - uid: Ceres.Editor.Graph
    name: Graph
    isExternal: true
    href: Ceres.Editor.Graph.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Ceres.Editor.Graph.APIUpdateConfigEditor.OnInspectorGUI*
  commentId: Overload:Ceres.Editor.Graph.APIUpdateConfigEditor.OnInspectorGUI
  isExternal: true
  href: Ceres.Editor.Graph.APIUpdateConfigEditor.html#Ceres_Editor_Graph_APIUpdateConfigEditor_OnInspectorGUI
  name: OnInspectorGUI
  nameWithType: APIUpdateConfigEditor.OnInspectorGUI
  fullName: Ceres.Editor.Graph.APIUpdateConfigEditor.OnInspectorGUI
- uid: Ceres.Editor.Graph.APIUpdateConfigEditor.#ctor*
  commentId: Overload:Ceres.Editor.Graph.APIUpdateConfigEditor.#ctor
  isExternal: true
  href: Ceres.Editor.Graph.APIUpdateConfigEditor.html#Ceres_Editor_Graph_APIUpdateConfigEditor__ctor
  name: APIUpdateConfigEditor
  nameWithType: APIUpdateConfigEditor.APIUpdateConfigEditor
  fullName: Ceres.Editor.Graph.APIUpdateConfigEditor.APIUpdateConfigEditor
  nameWithType.vb: APIUpdateConfigEditor.New
  fullName.vb: Ceres.Editor.Graph.APIUpdateConfigEditor.New
  name.vb: New
