### YamlMime:ManagedReference
items:
- uid: Ceres.Gameplay.Editor.CeresGameplaySettings
  commentId: T:Ceres.Gameplay.Editor.CeresGameplaySettings
  id: CeresGameplaySettings
  parent: Ceres.Gameplay.Editor
  children:
  - Ceres.Gameplay.Editor.CeresGameplaySettings.#ctor
  - Ceres.Gameplay.Editor.CeresGameplaySettings.enableRemoteUpdate
  - Ceres.Gameplay.Editor.CeresGameplaySettings.remoteUpdateSerializeMode
  - Ceres.Gameplay.Editor.CeresGameplaySettings.subsystemForceInitializeBeforeGet
  langs:
  - csharp
  - vb
  name: CeresGameplaySettings
  nameWithType: CeresGameplaySettings
  fullName: Ceres.Gameplay.Editor.CeresGameplaySettings
  type: Class
  assemblies:
  - Ceres.Gameplay.Editor
  namespace: Ceres.Gameplay.Editor
  syntax:
    content: >-
      [BaseConfig]

      public class CeresGameplaySettings : ConfigSingleton<CeresGameplaySettings>
    content.vb: >-
      <BaseConfig>

      Public Class CeresGameplaySettings Inherits ConfigSingleton(Of CeresGameplaySettings)
  inheritance:
  - System.Object
  - Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}
  inheritedMembers:
  - Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Save(System.Boolean)
  - Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Serialize(Ceres.Configs.ConfigBase)
  - Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Serialize(Ceres.Configs.ConfigFileLocation,Ceres.Configs.IConfigFile)
  - Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Instance
  attributes:
  - type: Ceres.Editor.BaseConfigAttribute
    ctor: Ceres.Editor.BaseConfigAttribute.#ctor
    arguments: []
- uid: Ceres.Gameplay.Editor.CeresGameplaySettings.enableRemoteUpdate
  commentId: F:Ceres.Gameplay.Editor.CeresGameplaySettings.enableRemoteUpdate
  id: enableRemoteUpdate
  parent: Ceres.Gameplay.Editor.CeresGameplaySettings
  langs:
  - csharp
  - vb
  name: enableRemoteUpdate
  nameWithType: CeresGameplaySettings.enableRemoteUpdate
  fullName: Ceres.Gameplay.Editor.CeresGameplaySettings.enableRemoteUpdate
  type: Field
  assemblies:
  - Ceres.Gameplay.Editor
  namespace: Ceres.Gameplay.Editor
  syntax:
    content: public bool enableRemoteUpdate
    return:
      type: System.Boolean
    content.vb: Public enableRemoteUpdate As Boolean
- uid: Ceres.Gameplay.Editor.CeresGameplaySettings.remoteUpdateSerializeMode
  commentId: F:Ceres.Gameplay.Editor.CeresGameplaySettings.remoteUpdateSerializeMode
  id: remoteUpdateSerializeMode
  parent: Ceres.Gameplay.Editor.CeresGameplaySettings
  langs:
  - csharp
  - vb
  name: remoteUpdateSerializeMode
  nameWithType: CeresGameplaySettings.remoteUpdateSerializeMode
  fullName: Ceres.Gameplay.Editor.CeresGameplaySettings.remoteUpdateSerializeMode
  type: Field
  assemblies:
  - Ceres.Gameplay.Editor
  namespace: Ceres.Gameplay.Editor
  syntax:
    content: public RemoteUpdateSerializeMode remoteUpdateSerializeMode
    return:
      type: Ceres.Gameplay.Editor.RemoteUpdateSerializeMode
    content.vb: Public remoteUpdateSerializeMode As RemoteUpdateSerializeMode
- uid: Ceres.Gameplay.Editor.CeresGameplaySettings.subsystemForceInitializeBeforeGet
  commentId: F:Ceres.Gameplay.Editor.CeresGameplaySettings.subsystemForceInitializeBeforeGet
  id: subsystemForceInitializeBeforeGet
  parent: Ceres.Gameplay.Editor.CeresGameplaySettings
  langs:
  - csharp
  - vb
  name: subsystemForceInitializeBeforeGet
  nameWithType: CeresGameplaySettings.subsystemForceInitializeBeforeGet
  fullName: Ceres.Gameplay.Editor.CeresGameplaySettings.subsystemForceInitializeBeforeGet
  type: Field
  assemblies:
  - Ceres.Gameplay.Editor
  namespace: Ceres.Gameplay.Editor
  syntax:
    content: public bool subsystemForceInitializeBeforeGet
    return:
      type: System.Boolean
    content.vb: Public subsystemForceInitializeBeforeGet As Boolean
- uid: Ceres.Gameplay.Editor.CeresGameplaySettings.#ctor
  commentId: M:Ceres.Gameplay.Editor.CeresGameplaySettings.#ctor
  id: '#ctor'
  parent: Ceres.Gameplay.Editor.CeresGameplaySettings
  langs:
  - csharp
  - vb
  name: CeresGameplaySettings()
  nameWithType: CeresGameplaySettings.CeresGameplaySettings()
  fullName: Ceres.Gameplay.Editor.CeresGameplaySettings.CeresGameplaySettings()
  type: Constructor
  assemblies:
  - Ceres.Gameplay.Editor
  namespace: Ceres.Gameplay.Editor
  syntax:
    content: public CeresGameplaySettings()
    content.vb: Public Sub New()
  overload: Ceres.Gameplay.Editor.CeresGameplaySettings.#ctor*
  nameWithType.vb: CeresGameplaySettings.New()
  fullName.vb: Ceres.Gameplay.Editor.CeresGameplaySettings.New()
  name.vb: New()
references:
- uid: Ceres.Gameplay.Editor
  commentId: N:Ceres.Gameplay.Editor
  isExternal: true
  href: Ceres.html
  name: Ceres.Gameplay.Editor
  nameWithType: Ceres.Gameplay.Editor
  fullName: Ceres.Gameplay.Editor
  spec.csharp:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Gameplay
    name: Gameplay
    isExternal: true
    href: Ceres.Gameplay.html
  - name: .
  - uid: Ceres.Gameplay.Editor
    name: Editor
    isExternal: true
    href: Ceres.Gameplay.Editor.html
  spec.vb:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Gameplay
    name: Gameplay
    isExternal: true
    href: Ceres.Gameplay.html
  - name: .
  - uid: Ceres.Gameplay.Editor
    name: Editor
    isExternal: true
    href: Ceres.Gameplay.Editor.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}
  commentId: T:Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}
  parent: Ceres.Editor
  definition: Ceres.Editor.ConfigSingleton`1
  href: Ceres.Gameplay.Editor.CeresGameplaySettings.html
  name: ConfigSingleton<CeresGameplaySettings>
  nameWithType: ConfigSingleton<CeresGameplaySettings>
  fullName: Ceres.Editor.ConfigSingleton<Ceres.Gameplay.Editor.CeresGameplaySettings>
  nameWithType.vb: ConfigSingleton(Of CeresGameplaySettings)
  fullName.vb: Ceres.Editor.ConfigSingleton(Of Ceres.Gameplay.Editor.CeresGameplaySettings)
  name.vb: ConfigSingleton(Of CeresGameplaySettings)
  spec.csharp:
  - uid: Ceres.Editor.ConfigSingleton`1
    name: ConfigSingleton
    isExternal: true
  - name: <
  - uid: Ceres.Gameplay.Editor.CeresGameplaySettings
    name: CeresGameplaySettings
    isExternal: true
    href: Ceres.Gameplay.Editor.CeresGameplaySettings.html
  - name: '>'
  spec.vb:
  - uid: Ceres.Editor.ConfigSingleton`1
    name: ConfigSingleton
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: Ceres.Gameplay.Editor.CeresGameplaySettings
    name: CeresGameplaySettings
    isExternal: true
    href: Ceres.Gameplay.Editor.CeresGameplaySettings.html
  - name: )
- uid: Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Save(System.Boolean)
  commentId: M:Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Save(System.Boolean)
  parent: Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}
  definition: Ceres.Editor.ConfigSingleton`1.Save(System.Boolean)
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: Save(bool)
  nameWithType: ConfigSingleton<CeresGameplaySettings>.Save(bool)
  fullName: Ceres.Editor.ConfigSingleton<Ceres.Gameplay.Editor.CeresGameplaySettings>.Save(bool)
  nameWithType.vb: ConfigSingleton(Of CeresGameplaySettings).Save(Boolean)
  fullName.vb: Ceres.Editor.ConfigSingleton(Of Ceres.Gameplay.Editor.CeresGameplaySettings).Save(Boolean)
  name.vb: Save(Boolean)
  spec.csharp:
  - uid: Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Save(System.Boolean)
    name: Save
    isExternal: true
  - name: (
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: )
  spec.vb:
  - uid: Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Save(System.Boolean)
    name: Save
    isExternal: true
  - name: (
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: )
- uid: Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Serialize(Ceres.Configs.ConfigBase)
  commentId: M:Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Serialize(Ceres.Configs.ConfigBase)
  parent: Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}
  definition: Ceres.Editor.ConfigSingleton`1.Serialize(Ceres.Configs.ConfigBase)
  name: Serialize(ConfigBase)
  nameWithType: ConfigSingleton<CeresGameplaySettings>.Serialize(ConfigBase)
  fullName: Ceres.Editor.ConfigSingleton<Ceres.Gameplay.Editor.CeresGameplaySettings>.Serialize(Ceres.Configs.ConfigBase)
  nameWithType.vb: ConfigSingleton(Of CeresGameplaySettings).Serialize(ConfigBase)
  fullName.vb: Ceres.Editor.ConfigSingleton(Of Ceres.Gameplay.Editor.CeresGameplaySettings).Serialize(Ceres.Configs.ConfigBase)
  spec.csharp:
  - uid: Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Serialize(Ceres.Configs.ConfigBase)
    name: Serialize
    isExternal: true
  - name: (
  - uid: Ceres.Configs.ConfigBase
    name: ConfigBase
    isExternal: true
  - name: )
  spec.vb:
  - uid: Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Serialize(Ceres.Configs.ConfigBase)
    name: Serialize
    isExternal: true
  - name: (
  - uid: Ceres.Configs.ConfigBase
    name: ConfigBase
    isExternal: true
  - name: )
- uid: Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Serialize(Ceres.Configs.ConfigFileLocation,Ceres.Configs.IConfigFile)
  commentId: M:Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Serialize(Ceres.Configs.ConfigFileLocation,Ceres.Configs.IConfigFile)
  parent: Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}
  definition: Ceres.Editor.ConfigSingleton`1.Serialize(Ceres.Configs.ConfigFileLocation,Ceres.Configs.IConfigFile)
  name: Serialize(ConfigFileLocation, IConfigFile)
  nameWithType: ConfigSingleton<CeresGameplaySettings>.Serialize(ConfigFileLocation, IConfigFile)
  fullName: Ceres.Editor.ConfigSingleton<Ceres.Gameplay.Editor.CeresGameplaySettings>.Serialize(Ceres.Configs.ConfigFileLocation, Ceres.Configs.IConfigFile)
  nameWithType.vb: ConfigSingleton(Of CeresGameplaySettings).Serialize(ConfigFileLocation, IConfigFile)
  fullName.vb: Ceres.Editor.ConfigSingleton(Of Ceres.Gameplay.Editor.CeresGameplaySettings).Serialize(Ceres.Configs.ConfigFileLocation, Ceres.Configs.IConfigFile)
  spec.csharp:
  - uid: Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Serialize(Ceres.Configs.ConfigFileLocation,Ceres.Configs.IConfigFile)
    name: Serialize
    isExternal: true
  - name: (
  - uid: Ceres.Configs.ConfigFileLocation
    name: ConfigFileLocation
    isExternal: true
  - name: ','
  - name: " "
  - uid: Ceres.Configs.IConfigFile
    name: IConfigFile
    isExternal: true
  - name: )
  spec.vb:
  - uid: Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Serialize(Ceres.Configs.ConfigFileLocation,Ceres.Configs.IConfigFile)
    name: Serialize
    isExternal: true
  - name: (
  - uid: Ceres.Configs.ConfigFileLocation
    name: ConfigFileLocation
    isExternal: true
  - name: ','
  - name: " "
  - uid: Ceres.Configs.IConfigFile
    name: IConfigFile
    isExternal: true
  - name: )
- uid: Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Instance
  commentId: P:Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}.Instance
  parent: Ceres.Editor.ConfigSingleton{Ceres.Gameplay.Editor.CeresGameplaySettings}
  definition: Ceres.Editor.ConfigSingleton`1.Instance
  name: Instance
  nameWithType: ConfigSingleton<CeresGameplaySettings>.Instance
  fullName: Ceres.Editor.ConfigSingleton<Ceres.Gameplay.Editor.CeresGameplaySettings>.Instance
  nameWithType.vb: ConfigSingleton(Of CeresGameplaySettings).Instance
  fullName.vb: Ceres.Editor.ConfigSingleton(Of Ceres.Gameplay.Editor.CeresGameplaySettings).Instance
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Ceres.Editor.ConfigSingleton`1
  commentId: T:Ceres.Editor.ConfigSingleton`1
  isExternal: true
  href: Ceres.Editor.ConfigSingleton-1.html
  name: ConfigSingleton<T>
  nameWithType: ConfigSingleton<T>
  fullName: Ceres.Editor.ConfigSingleton<T>
  nameWithType.vb: ConfigSingleton(Of T)
  fullName.vb: Ceres.Editor.ConfigSingleton(Of T)
  name.vb: ConfigSingleton(Of T)
  spec.csharp:
  - uid: Ceres.Editor.ConfigSingleton`1
    name: ConfigSingleton
    isExternal: true
    href: Ceres.Editor.ConfigSingleton-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Ceres.Editor.ConfigSingleton`1
    name: ConfigSingleton
    isExternal: true
    href: Ceres.Editor.ConfigSingleton-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Ceres.Editor
  commentId: N:Ceres.Editor
  isExternal: true
  href: Ceres.html
  name: Ceres.Editor
  nameWithType: Ceres.Editor
  fullName: Ceres.Editor
  spec.csharp:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Editor
    name: Editor
    isExternal: true
    href: Ceres.Editor.html
  spec.vb:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Editor
    name: Editor
    isExternal: true
    href: Ceres.Editor.html
- uid: Ceres.Editor.ConfigSingleton`1.Save(System.Boolean)
  commentId: M:Ceres.Editor.ConfigSingleton`1.Save(System.Boolean)
  isExternal: true
  href: Ceres.Editor.ConfigSingleton-1.html#Ceres_Editor_ConfigSingleton_1_Save_System_Boolean_
  name: Save(bool)
  nameWithType: ConfigSingleton<T>.Save(bool)
  fullName: Ceres.Editor.ConfigSingleton<T>.Save(bool)
  nameWithType.vb: ConfigSingleton(Of T).Save(Boolean)
  fullName.vb: Ceres.Editor.ConfigSingleton(Of T).Save(Boolean)
  name.vb: Save(Boolean)
  spec.csharp:
  - uid: Ceres.Editor.ConfigSingleton`1.Save(System.Boolean)
    name: Save
    isExternal: true
    href: Ceres.Editor.ConfigSingleton-1.html#Ceres_Editor_ConfigSingleton_1_Save_System_Boolean_
  - name: (
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: )
  spec.vb:
  - uid: Ceres.Editor.ConfigSingleton`1.Save(System.Boolean)
    name: Save
    isExternal: true
    href: Ceres.Editor.ConfigSingleton-1.html#Ceres_Editor_ConfigSingleton_1_Save_System_Boolean_
  - name: (
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: )
- uid: Ceres.Editor.ConfigSingleton`1.Serialize(Ceres.Configs.ConfigBase)
  commentId: M:Ceres.Editor.ConfigSingleton`1.Serialize(Ceres.Configs.ConfigBase)
  isExternal: true
  href: Ceres.Editor.ConfigSingleton-1.html#Ceres_Editor_ConfigSingleton_1_Serialize_Ceres_Configs_ConfigBase_
  name: Serialize(ConfigBase)
  nameWithType: ConfigSingleton<T>.Serialize(ConfigBase)
  fullName: Ceres.Editor.ConfigSingleton<T>.Serialize(Ceres.Configs.ConfigBase)
  nameWithType.vb: ConfigSingleton(Of T).Serialize(ConfigBase)
  fullName.vb: Ceres.Editor.ConfigSingleton(Of T).Serialize(Ceres.Configs.ConfigBase)
  spec.csharp:
  - uid: Ceres.Editor.ConfigSingleton`1.Serialize(Ceres.Configs.ConfigBase)
    name: Serialize
    isExternal: true
    href: Ceres.Editor.ConfigSingleton-1.html#Ceres_Editor_ConfigSingleton_1_Serialize_Ceres_Configs_ConfigBase_
  - name: (
  - uid: Ceres.Configs.ConfigBase
    name: ConfigBase
    isExternal: true
  - name: )
  spec.vb:
  - uid: Ceres.Editor.ConfigSingleton`1.Serialize(Ceres.Configs.ConfigBase)
    name: Serialize
    isExternal: true
    href: Ceres.Editor.ConfigSingleton-1.html#Ceres_Editor_ConfigSingleton_1_Serialize_Ceres_Configs_ConfigBase_
  - name: (
  - uid: Ceres.Configs.ConfigBase
    name: ConfigBase
    isExternal: true
  - name: )
- uid: Ceres.Editor.ConfigSingleton`1.Serialize(Ceres.Configs.ConfigFileLocation,Ceres.Configs.IConfigFile)
  commentId: M:Ceres.Editor.ConfigSingleton`1.Serialize(Ceres.Configs.ConfigFileLocation,Ceres.Configs.IConfigFile)
  isExternal: true
  href: Ceres.Editor.ConfigSingleton-1.html#Ceres_Editor_ConfigSingleton_1_Serialize_Ceres_Configs_ConfigFileLocation_Ceres_Configs_IConfigFile_
  name: Serialize(ConfigFileLocation, IConfigFile)
  nameWithType: ConfigSingleton<T>.Serialize(ConfigFileLocation, IConfigFile)
  fullName: Ceres.Editor.ConfigSingleton<T>.Serialize(Ceres.Configs.ConfigFileLocation, Ceres.Configs.IConfigFile)
  nameWithType.vb: ConfigSingleton(Of T).Serialize(ConfigFileLocation, IConfigFile)
  fullName.vb: Ceres.Editor.ConfigSingleton(Of T).Serialize(Ceres.Configs.ConfigFileLocation, Ceres.Configs.IConfigFile)
  spec.csharp:
  - uid: Ceres.Editor.ConfigSingleton`1.Serialize(Ceres.Configs.ConfigFileLocation,Ceres.Configs.IConfigFile)
    name: Serialize
    isExternal: true
    href: Ceres.Editor.ConfigSingleton-1.html#Ceres_Editor_ConfigSingleton_1_Serialize_Ceres_Configs_ConfigFileLocation_Ceres_Configs_IConfigFile_
  - name: (
  - uid: Ceres.Configs.ConfigFileLocation
    name: ConfigFileLocation
    isExternal: true
  - name: ','
  - name: " "
  - uid: Ceres.Configs.IConfigFile
    name: IConfigFile
    isExternal: true
  - name: )
  spec.vb:
  - uid: Ceres.Editor.ConfigSingleton`1.Serialize(Ceres.Configs.ConfigFileLocation,Ceres.Configs.IConfigFile)
    name: Serialize
    isExternal: true
    href: Ceres.Editor.ConfigSingleton-1.html#Ceres_Editor_ConfigSingleton_1_Serialize_Ceres_Configs_ConfigFileLocation_Ceres_Configs_IConfigFile_
  - name: (
  - uid: Ceres.Configs.ConfigFileLocation
    name: ConfigFileLocation
    isExternal: true
  - name: ','
  - name: " "
  - uid: Ceres.Configs.IConfigFile
    name: IConfigFile
    isExternal: true
  - name: )
- uid: Ceres.Editor.ConfigSingleton`1.Instance
  commentId: P:Ceres.Editor.ConfigSingleton`1.Instance
  isExternal: true
  href: Ceres.Editor.ConfigSingleton-1.html#Ceres_Editor_ConfigSingleton_1_Instance
  name: Instance
  nameWithType: ConfigSingleton<T>.Instance
  fullName: Ceres.Editor.ConfigSingleton<T>.Instance
  nameWithType.vb: ConfigSingleton(Of T).Instance
  fullName.vb: Ceres.Editor.ConfigSingleton(Of T).Instance
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Ceres.Gameplay.Editor.RemoteUpdateSerializeMode
  commentId: T:Ceres.Gameplay.Editor.RemoteUpdateSerializeMode
  parent: Ceres.Gameplay.Editor
  isExternal: true
  href: Ceres.Gameplay.Editor.RemoteUpdateSerializeMode.html
  name: RemoteUpdateSerializeMode
  nameWithType: RemoteUpdateSerializeMode
  fullName: Ceres.Gameplay.Editor.RemoteUpdateSerializeMode
- uid: Ceres.Gameplay.Editor.CeresGameplaySettings.#ctor*
  commentId: Overload:Ceres.Gameplay.Editor.CeresGameplaySettings.#ctor
  isExternal: true
  href: Ceres.Gameplay.Editor.CeresGameplaySettings.html#Ceres_Gameplay_Editor_CeresGameplaySettings__ctor
  name: CeresGameplaySettings
  nameWithType: CeresGameplaySettings.CeresGameplaySettings
  fullName: Ceres.Gameplay.Editor.CeresGameplaySettings.CeresGameplaySettings
  nameWithType.vb: CeresGameplaySettings.New
  fullName.vb: Ceres.Gameplay.Editor.CeresGameplaySettings.New
  name.vb: New
