### YamlMime:ManagedReference
items:
- uid: Ceres.Configs
  commentId: N:Ceres.Configs
  id: Ceres.Configs
  children:
  - Ceres.Configs.BoolConfigVariable`1
  - Ceres.Configs.ConfigBase
  - Ceres.Configs.ConfigFileLocation
  - Ceres.Configs.ConfigPathAttribute
  - Ceres.Configs.ConfigSystem
  - Ceres.Configs.ConfigVariable
  - Ceres.Configs.ConfigVariableAttribute
  - Ceres.Configs.ConfigVariableRegistry
  - Ceres.Configs.ConfigVariable`2
  - Ceres.Configs.Config`1
  - Ceres.Configs.ConfigsConfig
  - Ceres.Configs.ConfigsModule
  - Ceres.Configs.FieldAccessor
  - Ceres.Configs.FloatConfigVariable`1
  - Ceres.Configs.IConfigFile
  - Ceres.Configs.IConfigFileProvider
  - Ceres.Configs.IConfigLocation
  - Ceres.Configs.IntConfigVariable`1
  - Ceres.Configs.MemberAccessor
  - Ceres.Configs.PropertyAccessor
  - Ceres.Configs.ReactivePropertyAccessor
  - Ceres.Configs.StringConfigVariable`1
  langs:
  - csharp
  - vb
  name: Ceres.Configs
  nameWithType: Ceres.Configs
  fullName: Ceres.Configs
  type: Namespace
  assemblies:
  - Ceres
references:
- uid: Ceres.Configs.ConfigPathAttribute
  commentId: T:Ceres.Configs.ConfigPathAttribute
  parent: Ceres.Configs
  isExternal: true
  href: Ceres.Configs.ConfigPathAttribute.html
  name: ConfigPathAttribute
  nameWithType: ConfigPathAttribute
  fullName: Ceres.Configs.ConfigPathAttribute
- uid: Ceres.Configs.ConfigVariableAttribute
  commentId: T:Ceres.Configs.ConfigVariableAttribute
  isExternal: true
  href: Ceres.Configs.ConfigVariableAttribute.html
  name: ConfigVariableAttribute
  nameWithType: ConfigVariableAttribute
  fullName: Ceres.Configs.ConfigVariableAttribute
- uid: Ceres.Configs.ConfigBase
  commentId: T:Ceres.Configs.ConfigBase
  parent: Ceres.Configs
  isExternal: true
  href: Ceres.Configs.ConfigBase.html
  name: ConfigBase
  nameWithType: ConfigBase
  fullName: Ceres.Configs.ConfigBase
- uid: Ceres.Configs.Config`1
  commentId: T:Ceres.Configs.Config`1
  isExternal: true
  href: Ceres.Configs.Config-1.html
  name: Config<TConfig>
  nameWithType: Config<TConfig>
  fullName: Ceres.Configs.Config<TConfig>
  nameWithType.vb: Config(Of TConfig)
  fullName.vb: Ceres.Configs.Config(Of TConfig)
  name.vb: Config(Of TConfig)
  spec.csharp:
  - uid: Ceres.Configs.Config`1
    name: Config
    isExternal: true
    href: Ceres.Configs.Config-1.html
  - name: <
  - name: TConfig
  - name: '>'
  spec.vb:
  - uid: Ceres.Configs.Config`1
    name: Config
    isExternal: true
    href: Ceres.Configs.Config-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TConfig
  - name: )
- uid: Ceres.Configs.IConfigLocation
  commentId: T:Ceres.Configs.IConfigLocation
  parent: Ceres.Configs
  isExternal: true
  href: Ceres.Configs.IConfigLocation.html
  name: IConfigLocation
  nameWithType: IConfigLocation
  fullName: Ceres.Configs.IConfigLocation
- uid: Ceres.Configs.ConfigFileLocation
  commentId: T:Ceres.Configs.ConfigFileLocation
  parent: Ceres.Configs
  isExternal: true
  href: Ceres.Configs.ConfigFileLocation.html
  name: ConfigFileLocation
  nameWithType: ConfigFileLocation
  fullName: Ceres.Configs.ConfigFileLocation
- uid: Ceres.Configs.IConfigFileProvider
  commentId: T:Ceres.Configs.IConfigFileProvider
  parent: Ceres.Configs
  isExternal: true
  href: Ceres.Configs.IConfigFileProvider.html
  name: IConfigFileProvider
  nameWithType: IConfigFileProvider
  fullName: Ceres.Configs.IConfigFileProvider
- uid: Ceres.Configs.IConfigFile
  commentId: T:Ceres.Configs.IConfigFile
  parent: Ceres.Configs
  isExternal: true
  href: Ceres.Configs.IConfigFile.html
  name: IConfigFile
  nameWithType: IConfigFile
  fullName: Ceres.Configs.IConfigFile
- uid: Ceres.Configs.ConfigSystem
  commentId: T:Ceres.Configs.ConfigSystem
  isExternal: true
  href: Ceres.Configs.ConfigSystem.html
  name: ConfigSystem
  nameWithType: ConfigSystem
  fullName: Ceres.Configs.ConfigSystem
- uid: Ceres.Configs.MemberAccessor
  commentId: T:Ceres.Configs.MemberAccessor
  parent: Ceres.Configs
  isExternal: true
  href: Ceres.Configs.MemberAccessor.html
  name: MemberAccessor
  nameWithType: MemberAccessor
  fullName: Ceres.Configs.MemberAccessor
- uid: Ceres.Configs.FieldAccessor
  commentId: T:Ceres.Configs.FieldAccessor
  isExternal: true
  href: Ceres.Configs.FieldAccessor.html
  name: FieldAccessor
  nameWithType: FieldAccessor
  fullName: Ceres.Configs.FieldAccessor
- uid: Ceres.Configs.PropertyAccessor
  commentId: T:Ceres.Configs.PropertyAccessor
  isExternal: true
  href: Ceres.Configs.PropertyAccessor.html
  name: PropertyAccessor
  nameWithType: PropertyAccessor
  fullName: Ceres.Configs.PropertyAccessor
- uid: Ceres.Configs.ReactivePropertyAccessor
  commentId: T:Ceres.Configs.ReactivePropertyAccessor
  isExternal: true
  href: Ceres.Configs.ReactivePropertyAccessor.html
  name: ReactivePropertyAccessor
  nameWithType: ReactivePropertyAccessor
  fullName: Ceres.Configs.ReactivePropertyAccessor
- uid: Ceres.Configs.ConfigVariable
  commentId: T:Ceres.Configs.ConfigVariable
  parent: Ceres.Configs
  isExternal: true
  href: Ceres.Configs.ConfigVariable.html
  name: ConfigVariable
  nameWithType: ConfigVariable
  fullName: Ceres.Configs.ConfigVariable
- uid: Ceres.Configs.ConfigVariable`2
  commentId: T:Ceres.Configs.ConfigVariable`2
  isExternal: true
  href: Ceres.Configs.ConfigVariable-2.html
  name: ConfigVariable<TConfig, TValue>
  nameWithType: ConfigVariable<TConfig, TValue>
  fullName: Ceres.Configs.ConfigVariable<TConfig, TValue>
  nameWithType.vb: ConfigVariable(Of TConfig, TValue)
  fullName.vb: Ceres.Configs.ConfigVariable(Of TConfig, TValue)
  name.vb: ConfigVariable(Of TConfig, TValue)
  spec.csharp:
  - uid: Ceres.Configs.ConfigVariable`2
    name: ConfigVariable
    isExternal: true
    href: Ceres.Configs.ConfigVariable-2.html
  - name: <
  - name: TConfig
  - name: ','
  - name: " "
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: Ceres.Configs.ConfigVariable`2
    name: ConfigVariable
    isExternal: true
    href: Ceres.Configs.ConfigVariable-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TConfig
  - name: ','
  - name: " "
  - name: TValue
  - name: )
- uid: Ceres.Configs.IntConfigVariable`1
  commentId: T:Ceres.Configs.IntConfigVariable`1
  isExternal: true
  href: Ceres.Configs.IntConfigVariable-1.html
  name: IntConfigVariable<TConfig>
  nameWithType: IntConfigVariable<TConfig>
  fullName: Ceres.Configs.IntConfigVariable<TConfig>
  nameWithType.vb: IntConfigVariable(Of TConfig)
  fullName.vb: Ceres.Configs.IntConfigVariable(Of TConfig)
  name.vb: IntConfigVariable(Of TConfig)
  spec.csharp:
  - uid: Ceres.Configs.IntConfigVariable`1
    name: IntConfigVariable
    isExternal: true
    href: Ceres.Configs.IntConfigVariable-1.html
  - name: <
  - name: TConfig
  - name: '>'
  spec.vb:
  - uid: Ceres.Configs.IntConfigVariable`1
    name: IntConfigVariable
    isExternal: true
    href: Ceres.Configs.IntConfigVariable-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TConfig
  - name: )
- uid: Ceres.Configs.FloatConfigVariable`1
  commentId: T:Ceres.Configs.FloatConfigVariable`1
  isExternal: true
  href: Ceres.Configs.FloatConfigVariable-1.html
  name: FloatConfigVariable<TConfig>
  nameWithType: FloatConfigVariable<TConfig>
  fullName: Ceres.Configs.FloatConfigVariable<TConfig>
  nameWithType.vb: FloatConfigVariable(Of TConfig)
  fullName.vb: Ceres.Configs.FloatConfigVariable(Of TConfig)
  name.vb: FloatConfigVariable(Of TConfig)
  spec.csharp:
  - uid: Ceres.Configs.FloatConfigVariable`1
    name: FloatConfigVariable
    isExternal: true
    href: Ceres.Configs.FloatConfigVariable-1.html
  - name: <
  - name: TConfig
  - name: '>'
  spec.vb:
  - uid: Ceres.Configs.FloatConfigVariable`1
    name: FloatConfigVariable
    isExternal: true
    href: Ceres.Configs.FloatConfigVariable-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TConfig
  - name: )
- uid: Ceres.Configs.BoolConfigVariable`1
  commentId: T:Ceres.Configs.BoolConfigVariable`1
  isExternal: true
  href: Ceres.Configs.BoolConfigVariable-1.html
  name: BoolConfigVariable<TConfig>
  nameWithType: BoolConfigVariable<TConfig>
  fullName: Ceres.Configs.BoolConfigVariable<TConfig>
  nameWithType.vb: BoolConfigVariable(Of TConfig)
  fullName.vb: Ceres.Configs.BoolConfigVariable(Of TConfig)
  name.vb: BoolConfigVariable(Of TConfig)
  spec.csharp:
  - uid: Ceres.Configs.BoolConfigVariable`1
    name: BoolConfigVariable
    isExternal: true
    href: Ceres.Configs.BoolConfigVariable-1.html
  - name: <
  - name: TConfig
  - name: '>'
  spec.vb:
  - uid: Ceres.Configs.BoolConfigVariable`1
    name: BoolConfigVariable
    isExternal: true
    href: Ceres.Configs.BoolConfigVariable-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TConfig
  - name: )
- uid: Ceres.Configs.StringConfigVariable`1
  commentId: T:Ceres.Configs.StringConfigVariable`1
  isExternal: true
  href: Ceres.Configs.StringConfigVariable-1.html
  name: StringConfigVariable<TConfig>
  nameWithType: StringConfigVariable<TConfig>
  fullName: Ceres.Configs.StringConfigVariable<TConfig>
  nameWithType.vb: StringConfigVariable(Of TConfig)
  fullName.vb: Ceres.Configs.StringConfigVariable(Of TConfig)
  name.vb: StringConfigVariable(Of TConfig)
  spec.csharp:
  - uid: Ceres.Configs.StringConfigVariable`1
    name: StringConfigVariable
    isExternal: true
    href: Ceres.Configs.StringConfigVariable-1.html
  - name: <
  - name: TConfig
  - name: '>'
  spec.vb:
  - uid: Ceres.Configs.StringConfigVariable`1
    name: StringConfigVariable
    isExternal: true
    href: Ceres.Configs.StringConfigVariable-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TConfig
  - name: )
- uid: Ceres.Configs.ConfigVariableRegistry
  commentId: T:Ceres.Configs.ConfigVariableRegistry
  parent: Ceres.Configs
  isExternal: true
  href: Ceres.Configs.ConfigVariableRegistry.html
  name: ConfigVariableRegistry
  nameWithType: ConfigVariableRegistry
  fullName: Ceres.Configs.ConfigVariableRegistry
- uid: Ceres.Configs.ConfigsConfig
  commentId: T:Ceres.Configs.ConfigsConfig
  isExternal: true
  href: Ceres.Configs.ConfigsConfig.html
  name: ConfigsConfig
  nameWithType: ConfigsConfig
  fullName: Ceres.Configs.ConfigsConfig
- uid: Ceres.Configs.ConfigsModule
  commentId: T:Ceres.Configs.ConfigsModule
  isExternal: true
  href: Ceres.Configs.ConfigsModule.html
  name: ConfigsModule
  nameWithType: ConfigsModule
  fullName: Ceres.Configs.ConfigsModule
- uid: Ceres.Configs
  commentId: N:Ceres.Configs
  isExternal: true
  href: Ceres.html
  name: Ceres.Configs
  nameWithType: Ceres.Configs
  fullName: Ceres.Configs
  spec.csharp:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Configs
    name: Configs
    isExternal: true
    href: Ceres.Configs.html
  spec.vb:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Configs
    name: Configs
    isExternal: true
    href: Ceres.Configs.html
