### YamlMime:ManagedReference
items:
- uid: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer
  commentId: T:Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer
  id: ActorFlowGraphSettingsDrawer
  parent: Ceres.Gameplay.Editor
  children:
  - Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.#ctor
  - Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.GetPropertyHeight(UnityEditor.SerializedProperty,UnityEngine.GUIContent)
  - Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.OnGUI(UnityEngine.Rect,UnityEditor.SerializedProperty,UnityEngine.GUIContent)
  langs:
  - csharp
  - vb
  name: ActorFlowGraphSettingsDrawer
  nameWithType: ActorFlowGraphSettingsDrawer
  fullName: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer
  type: Class
  assemblies:
  - Ceres.Gameplay.Editor
  namespace: Ceres.Gameplay.Editor
  syntax:
    content: 'public class ActorFlowGraphSettingsDrawer : PropertyDrawer'
    content.vb: Public Class ActorFlowGraphSettingsDrawer Inherits PropertyDrawer
  inheritance:
  - System.Object
- uid: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.OnGUI(UnityEngine.Rect,UnityEditor.SerializedProperty,UnityEngine.GUIContent)
  commentId: M:Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.OnGUI(UnityEngine.Rect,UnityEditor.SerializedProperty,UnityEngine.GUIContent)
  id: OnGUI(UnityEngine.Rect,UnityEditor.SerializedProperty,UnityEngine.GUIContent)
  parent: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer
  langs:
  - csharp
  - vb
  name: OnGUI(Rect, SerializedProperty, GUIContent)
  nameWithType: ActorFlowGraphSettingsDrawer.OnGUI(Rect, SerializedProperty, GUIContent)
  fullName: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.OnGUI(UnityEngine.Rect, UnityEditor.SerializedProperty, UnityEngine.GUIContent)
  type: Method
  assemblies:
  - Ceres.Gameplay.Editor
  namespace: Ceres.Gameplay.Editor
  example: []
  syntax:
    content: public override void OnGUI(Rect position, SerializedProperty property, GUIContent label)
    parameters:
    - id: position
      type: UnityEngine.Rect
    - id: property
      type: UnityEditor.SerializedProperty
    - id: label
      type: UnityEngine.GUIContent
    content.vb: Public Overrides Sub OnGUI(position As Rect, [property] As SerializedProperty, label As GUIContent)
  overload: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.OnGUI*
- uid: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.GetPropertyHeight(UnityEditor.SerializedProperty,UnityEngine.GUIContent)
  commentId: M:Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.GetPropertyHeight(UnityEditor.SerializedProperty,UnityEngine.GUIContent)
  id: GetPropertyHeight(UnityEditor.SerializedProperty,UnityEngine.GUIContent)
  parent: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer
  langs:
  - csharp
  - vb
  name: GetPropertyHeight(SerializedProperty, GUIContent)
  nameWithType: ActorFlowGraphSettingsDrawer.GetPropertyHeight(SerializedProperty, GUIContent)
  fullName: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.GetPropertyHeight(UnityEditor.SerializedProperty, UnityEngine.GUIContent)
  type: Method
  assemblies:
  - Ceres.Gameplay.Editor
  namespace: Ceres.Gameplay.Editor
  example: []
  syntax:
    content: public override float GetPropertyHeight(SerializedProperty property, GUIContent label)
    parameters:
    - id: property
      type: UnityEditor.SerializedProperty
    - id: label
      type: UnityEngine.GUIContent
    return:
      type: System.Single
    content.vb: Public Overrides Function GetPropertyHeight([property] As SerializedProperty, label As GUIContent) As Single
  overload: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.GetPropertyHeight*
- uid: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.#ctor
  commentId: M:Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.#ctor
  id: '#ctor'
  parent: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer
  langs:
  - csharp
  - vb
  name: ActorFlowGraphSettingsDrawer()
  nameWithType: ActorFlowGraphSettingsDrawer.ActorFlowGraphSettingsDrawer()
  fullName: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.ActorFlowGraphSettingsDrawer()
  type: Constructor
  assemblies:
  - Ceres.Gameplay.Editor
  namespace: Ceres.Gameplay.Editor
  syntax:
    content: public ActorFlowGraphSettingsDrawer()
    content.vb: Public Sub New()
  overload: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.#ctor*
  nameWithType.vb: ActorFlowGraphSettingsDrawer.New()
  fullName.vb: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.New()
  name.vb: New()
references:
- uid: Ceres.Gameplay.Editor
  commentId: N:Ceres.Gameplay.Editor
  isExternal: true
  href: Ceres.html
  name: Ceres.Gameplay.Editor
  nameWithType: Ceres.Gameplay.Editor
  fullName: Ceres.Gameplay.Editor
  spec.csharp:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Gameplay
    name: Gameplay
    isExternal: true
    href: Ceres.Gameplay.html
  - name: .
  - uid: Ceres.Gameplay.Editor
    name: Editor
    isExternal: true
    href: Ceres.Gameplay.Editor.html
  spec.vb:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Gameplay
    name: Gameplay
    isExternal: true
    href: Ceres.Gameplay.html
  - name: .
  - uid: Ceres.Gameplay.Editor
    name: Editor
    isExternal: true
    href: Ceres.Gameplay.Editor.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.OnGUI*
  commentId: Overload:Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.OnGUI
  isExternal: true
  href: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.html#Ceres_Gameplay_Editor_ActorFlowGraphSettingsDrawer_OnGUI_UnityEngine_Rect_UnityEditor_SerializedProperty_UnityEngine_GUIContent_
  name: OnGUI
  nameWithType: ActorFlowGraphSettingsDrawer.OnGUI
  fullName: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.OnGUI
- uid: UnityEngine.Rect
  isExternal: true
  name: Rect
  nameWithType: Rect
  fullName: UnityEngine.Rect
- uid: UnityEditor.SerializedProperty
  isExternal: true
  name: SerializedProperty
  nameWithType: SerializedProperty
  fullName: UnityEditor.SerializedProperty
- uid: UnityEngine.GUIContent
  isExternal: true
  name: GUIContent
  nameWithType: GUIContent
  fullName: UnityEngine.GUIContent
- uid: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.GetPropertyHeight*
  commentId: Overload:Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.GetPropertyHeight
  isExternal: true
  href: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.html#Ceres_Gameplay_Editor_ActorFlowGraphSettingsDrawer_GetPropertyHeight_UnityEditor_SerializedProperty_UnityEngine_GUIContent_
  name: GetPropertyHeight
  nameWithType: ActorFlowGraphSettingsDrawer.GetPropertyHeight
  fullName: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.GetPropertyHeight
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.#ctor*
  commentId: Overload:Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.#ctor
  isExternal: true
  href: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.html#Ceres_Gameplay_Editor_ActorFlowGraphSettingsDrawer__ctor
  name: ActorFlowGraphSettingsDrawer
  nameWithType: ActorFlowGraphSettingsDrawer.ActorFlowGraphSettingsDrawer
  fullName: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.ActorFlowGraphSettingsDrawer
  nameWithType.vb: ActorFlowGraphSettingsDrawer.New
  fullName.vb: Ceres.Gameplay.Editor.ActorFlowGraphSettingsDrawer.New
  name.vb: New
