### YamlMime:ManagedReference
items:
- uid: Ceres.CeresConfig
  commentId: T:Ceres.CeresConfig
  id: CeresConfig
  parent: Ceres
  children:
  - Ceres.CeresConfig.#ctor
  langs:
  - csharp
  - vb
  name: CeresConfig
  nameWithType: CeresConfig
  fullName: Ceres.CeresConfig
  type: Class
  assemblies:
  - Ceres.Graph
  namespace: Ceres
  syntax:
    content: >-
      [ConfigPath("Ceres.Ceres")]

      public class CeresConfig : Config<CeresConfig>
    content.vb: >-
      <ConfigPath("Ceres.Ceres")>

      Public Class CeresConfig Inherits Config(Of CeresConfig)
  inheritance:
  - System.Object
  - Ceres.Configs.ConfigBase
  - Ceres.Configs.Config{Ceres.CeresConfig}
  inheritedMembers:
  - Ceres.Configs.Config{Ceres.CeresConfig}.Get
  - Ceres.Configs.Config{Ceres.CeresConfig}.IsRoot
  - Ceres.Configs.Config{Ceres.CeresConfig}.ParentPath
  - Ceres.Configs.Config{Ceres.CeresConfig}.Name
  - Ceres.Configs.Config{Ceres.CeresConfig}.Location
  - Ceres.Configs.ConfigBase.NextConfigId
  - Ceres.Configs.ConfigBase.Save
  - Ceres.Configs.ConfigBase.Save(Ceres.Serialization.SaveLoadSerializer)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  attributes:
  - type: Ceres.Configs.ConfigPathAttribute
    ctor: Ceres.Configs.ConfigPathAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: Ceres.Ceres
- uid: Ceres.CeresConfig.#ctor
  commentId: M:Ceres.CeresConfig.#ctor
  id: '#ctor'
  parent: Ceres.CeresConfig
  langs:
  - csharp
  - vb
  name: CeresConfig()
  nameWithType: CeresConfig.CeresConfig()
  fullName: Ceres.CeresConfig.CeresConfig()
  type: Constructor
  assemblies:
  - Ceres.Graph
  namespace: Ceres
  syntax:
    content: public CeresConfig()
    content.vb: Public Sub New()
  overload: Ceres.CeresConfig.#ctor*
  nameWithType.vb: CeresConfig.New()
  fullName.vb: Ceres.CeresConfig.New()
  name.vb: New()
references:
- uid: Ceres
  commentId: N:Ceres
  isExternal: true
  href: Ceres.html
  name: Ceres
  nameWithType: Ceres
  fullName: Ceres
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Ceres.Configs.ConfigBase
  commentId: T:Ceres.Configs.ConfigBase
  parent: Ceres.Configs
  isExternal: true
  href: Ceres.Configs.ConfigBase.html
  name: ConfigBase
  nameWithType: ConfigBase
  fullName: Ceres.Configs.ConfigBase
- uid: Ceres.Configs.Config{Ceres.CeresConfig}
  commentId: T:Ceres.Configs.Config{Ceres.CeresConfig}
  parent: Ceres.Configs
  definition: Ceres.Configs.Config`1
  href: Ceres.CeresConfig.html
  name: Config<CeresConfig>
  nameWithType: Config<CeresConfig>
  fullName: Ceres.Configs.Config<Ceres.CeresConfig>
  nameWithType.vb: Config(Of CeresConfig)
  fullName.vb: Ceres.Configs.Config(Of Ceres.CeresConfig)
  name.vb: Config(Of CeresConfig)
  spec.csharp:
  - uid: Ceres.Configs.Config`1
    name: Config
    isExternal: true
  - name: <
  - uid: Ceres.CeresConfig
    name: CeresConfig
    isExternal: true
    href: Ceres.CeresConfig.html
  - name: '>'
  spec.vb:
  - uid: Ceres.Configs.Config`1
    name: Config
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: Ceres.CeresConfig
    name: CeresConfig
    isExternal: true
    href: Ceres.CeresConfig.html
  - name: )
- uid: Ceres.Configs.Config{Ceres.CeresConfig}.Get
  commentId: M:Ceres.Configs.Config{Ceres.CeresConfig}.Get
  parent: Ceres.Configs.Config{Ceres.CeresConfig}
  definition: Ceres.Configs.Config`1.Get
  name: Get()
  nameWithType: Config<CeresConfig>.Get()
  fullName: Ceres.Configs.Config<Ceres.CeresConfig>.Get()
  nameWithType.vb: Config(Of CeresConfig).Get()
  fullName.vb: Ceres.Configs.Config(Of Ceres.CeresConfig).Get()
  spec.csharp:
  - uid: Ceres.Configs.Config{Ceres.CeresConfig}.Get
    name: Get
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: Ceres.Configs.Config{Ceres.CeresConfig}.Get
    name: Get
    isExternal: true
  - name: (
  - name: )
- uid: Ceres.Configs.Config{Ceres.CeresConfig}.IsRoot
  commentId: P:Ceres.Configs.Config{Ceres.CeresConfig}.IsRoot
  parent: Ceres.Configs.Config{Ceres.CeresConfig}
  definition: Ceres.Configs.Config`1.IsRoot
  name: IsRoot
  nameWithType: Config<CeresConfig>.IsRoot
  fullName: Ceres.Configs.Config<Ceres.CeresConfig>.IsRoot
  nameWithType.vb: Config(Of CeresConfig).IsRoot
  fullName.vb: Ceres.Configs.Config(Of Ceres.CeresConfig).IsRoot
- uid: Ceres.Configs.Config{Ceres.CeresConfig}.ParentPath
  commentId: P:Ceres.Configs.Config{Ceres.CeresConfig}.ParentPath
  parent: Ceres.Configs.Config{Ceres.CeresConfig}
  definition: Ceres.Configs.Config`1.ParentPath
  name: ParentPath
  nameWithType: Config<CeresConfig>.ParentPath
  fullName: Ceres.Configs.Config<Ceres.CeresConfig>.ParentPath
  nameWithType.vb: Config(Of CeresConfig).ParentPath
  fullName.vb: Ceres.Configs.Config(Of Ceres.CeresConfig).ParentPath
- uid: Ceres.Configs.Config{Ceres.CeresConfig}.Name
  commentId: P:Ceres.Configs.Config{Ceres.CeresConfig}.Name
  parent: Ceres.Configs.Config{Ceres.CeresConfig}
  definition: Ceres.Configs.Config`1.Name
  name: Name
  nameWithType: Config<CeresConfig>.Name
  fullName: Ceres.Configs.Config<Ceres.CeresConfig>.Name
  nameWithType.vb: Config(Of CeresConfig).Name
  fullName.vb: Ceres.Configs.Config(Of Ceres.CeresConfig).Name
- uid: Ceres.Configs.Config{Ceres.CeresConfig}.Location
  commentId: P:Ceres.Configs.Config{Ceres.CeresConfig}.Location
  parent: Ceres.Configs.Config{Ceres.CeresConfig}
  definition: Ceres.Configs.Config`1.Location
  name: Location
  nameWithType: Config<CeresConfig>.Location
  fullName: Ceres.Configs.Config<Ceres.CeresConfig>.Location
  nameWithType.vb: Config(Of CeresConfig).Location
  fullName.vb: Ceres.Configs.Config(Of Ceres.CeresConfig).Location
- uid: Ceres.Configs.ConfigBase.NextConfigId
  commentId: F:Ceres.Configs.ConfigBase.NextConfigId
  parent: Ceres.Configs.ConfigBase
  isExternal: true
  href: Ceres.Configs.ConfigBase.html#Ceres_Configs_ConfigBase_NextConfigId
  name: NextConfigId
  nameWithType: ConfigBase.NextConfigId
  fullName: Ceres.Configs.ConfigBase.NextConfigId
- uid: Ceres.Configs.ConfigBase.Save
  commentId: M:Ceres.Configs.ConfigBase.Save
  parent: Ceres.Configs.ConfigBase
  isExternal: true
  href: Ceres.Configs.ConfigBase.html#Ceres_Configs_ConfigBase_Save
  name: Save()
  nameWithType: ConfigBase.Save()
  fullName: Ceres.Configs.ConfigBase.Save()
  spec.csharp:
  - uid: Ceres.Configs.ConfigBase.Save
    name: Save
    isExternal: true
    href: Ceres.Configs.ConfigBase.html#Ceres_Configs_ConfigBase_Save
  - name: (
  - name: )
  spec.vb:
  - uid: Ceres.Configs.ConfigBase.Save
    name: Save
    isExternal: true
    href: Ceres.Configs.ConfigBase.html#Ceres_Configs_ConfigBase_Save
  - name: (
  - name: )
- uid: Ceres.Configs.ConfigBase.Save(Ceres.Serialization.SaveLoadSerializer)
  commentId: M:Ceres.Configs.ConfigBase.Save(Ceres.Serialization.SaveLoadSerializer)
  parent: Ceres.Configs.ConfigBase
  isExternal: true
  href: Ceres.Configs.ConfigBase.html#Ceres_Configs_ConfigBase_Save_Ceres_Serialization_SaveLoadSerializer_
  name: Save(SaveLoadSerializer)
  nameWithType: ConfigBase.Save(SaveLoadSerializer)
  fullName: Ceres.Configs.ConfigBase.Save(Ceres.Serialization.SaveLoadSerializer)
  spec.csharp:
  - uid: Ceres.Configs.ConfigBase.Save(Ceres.Serialization.SaveLoadSerializer)
    name: Save
    isExternal: true
    href: Ceres.Configs.ConfigBase.html#Ceres_Configs_ConfigBase_Save_Ceres_Serialization_SaveLoadSerializer_
  - name: (
  - uid: Ceres.Serialization.SaveLoadSerializer
    name: SaveLoadSerializer
    isExternal: true
    href: Ceres.Serialization.SaveLoadSerializer.html
  - name: )
  spec.vb:
  - uid: Ceres.Configs.ConfigBase.Save(Ceres.Serialization.SaveLoadSerializer)
    name: Save
    isExternal: true
    href: Ceres.Configs.ConfigBase.html#Ceres_Configs_ConfigBase_Save_Ceres_Serialization_SaveLoadSerializer_
  - name: (
  - uid: Ceres.Serialization.SaveLoadSerializer
    name: SaveLoadSerializer
    isExternal: true
    href: Ceres.Serialization.SaveLoadSerializer.html
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Ceres.Configs
  commentId: N:Ceres.Configs
  isExternal: true
  href: Ceres.html
  name: Ceres.Configs
  nameWithType: Ceres.Configs
  fullName: Ceres.Configs
  spec.csharp:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Configs
    name: Configs
    isExternal: true
    href: Ceres.Configs.html
  spec.vb:
  - uid: Ceres
    name: Ceres
    isExternal: true
    href: Ceres.html
  - name: .
  - uid: Ceres.Configs
    name: Configs
    isExternal: true
    href: Ceres.Configs.html
- uid: Ceres.Configs.Config`1
  commentId: T:Ceres.Configs.Config`1
  isExternal: true
  href: Ceres.Configs.Config-1.html
  name: Config<TConfig>
  nameWithType: Config<TConfig>
  fullName: Ceres.Configs.Config<TConfig>
  nameWithType.vb: Config(Of TConfig)
  fullName.vb: Ceres.Configs.Config(Of TConfig)
  name.vb: Config(Of TConfig)
  spec.csharp:
  - uid: Ceres.Configs.Config`1
    name: Config
    isExternal: true
    href: Ceres.Configs.Config-1.html
  - name: <
  - name: TConfig
  - name: '>'
  spec.vb:
  - uid: Ceres.Configs.Config`1
    name: Config
    isExternal: true
    href: Ceres.Configs.Config-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TConfig
  - name: )
- uid: Ceres.Configs.Config`1.Get
  commentId: M:Ceres.Configs.Config`1.Get
  isExternal: true
  href: Ceres.Configs.Config-1.html#Ceres_Configs_Config_1_Get
  name: Get()
  nameWithType: Config<TConfig>.Get()
  fullName: Ceres.Configs.Config<TConfig>.Get()
  nameWithType.vb: Config(Of TConfig).Get()
  fullName.vb: Ceres.Configs.Config(Of TConfig).Get()
  spec.csharp:
  - uid: Ceres.Configs.Config`1.Get
    name: Get
    isExternal: true
    href: Ceres.Configs.Config-1.html#Ceres_Configs_Config_1_Get
  - name: (
  - name: )
  spec.vb:
  - uid: Ceres.Configs.Config`1.Get
    name: Get
    isExternal: true
    href: Ceres.Configs.Config-1.html#Ceres_Configs_Config_1_Get
  - name: (
  - name: )
- uid: Ceres.Configs.Config`1.IsRoot
  commentId: P:Ceres.Configs.Config`1.IsRoot
  isExternal: true
  href: Ceres.Configs.Config-1.html#Ceres_Configs_Config_1_IsRoot
  name: IsRoot
  nameWithType: Config<TConfig>.IsRoot
  fullName: Ceres.Configs.Config<TConfig>.IsRoot
  nameWithType.vb: Config(Of TConfig).IsRoot
  fullName.vb: Ceres.Configs.Config(Of TConfig).IsRoot
- uid: Ceres.Configs.Config`1.ParentPath
  commentId: P:Ceres.Configs.Config`1.ParentPath
  isExternal: true
  href: Ceres.Configs.Config-1.html#Ceres_Configs_Config_1_ParentPath
  name: ParentPath
  nameWithType: Config<TConfig>.ParentPath
  fullName: Ceres.Configs.Config<TConfig>.ParentPath
  nameWithType.vb: Config(Of TConfig).ParentPath
  fullName.vb: Ceres.Configs.Config(Of TConfig).ParentPath
- uid: Ceres.Configs.Config`1.Name
  commentId: P:Ceres.Configs.Config`1.Name
  isExternal: true
  href: Ceres.Configs.Config-1.html#Ceres_Configs_Config_1_Name
  name: Name
  nameWithType: Config<TConfig>.Name
  fullName: Ceres.Configs.Config<TConfig>.Name
  nameWithType.vb: Config(Of TConfig).Name
  fullName.vb: Ceres.Configs.Config(Of TConfig).Name
- uid: Ceres.Configs.Config`1.Location
  commentId: P:Ceres.Configs.Config`1.Location
  isExternal: true
  href: Ceres.Configs.Config-1.html#Ceres_Configs_Config_1_Location
  name: Location
  nameWithType: Config<TConfig>.Location
  fullName: Ceres.Configs.Config<TConfig>.Location
  nameWithType.vb: Config(Of TConfig).Location
  fullName.vb: Ceres.Configs.Config(Of TConfig).Location
- uid: Ceres.CeresConfig.#ctor*
  commentId: Overload:Ceres.CeresConfig.#ctor
  isExternal: true
  href: Ceres.CeresConfig.html#Ceres_CeresConfig__ctor
  name: CeresConfig
  nameWithType: CeresConfig.CeresConfig
  fullName: Ceres.CeresConfig.CeresConfig
  nameWithType.vb: CeresConfig.New
  fullName.vb: Ceres.CeresConfig.New
  name.vb: New
