using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Ceres.Graph;
using Ceres.Graph.Flow;
using Ceres.Graph.Flow.CustomFunctions;
using Ceres.Graph.Flow.Properties;
using Ceres.Graph.Flow.Utilities;
using Ceres.Utilities;
using Chris.Serialization;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEditor.SceneManagement;
using UnityEngine;
using UObject = UnityEngine.Object;

namespace Ceres.Editor.Graph.Flow.CodeGen
{
    public static partial class FlowCSharpRuntimeGenerator
    {
        internal const string GenerateRuntimeMenuPath = "Tools/Ceres/Flow/Generate C# Runtime";
        internal const string OutputDirectory = "Assets/Ceres.Generated";
        internal const string GeneratedNamespace = "Ceres.Generated.Flow";
        internal const string GeneratedRegistryFileName = "FlowGeneratedProgramRegistry.generated.cs";
        internal const string GeneratedManifestFileName = "FlowGeneratedProgramManifest.json";
        internal const string GeneratedRegistryClassName = "FlowGeneratedProgramRegistryBootstrap";
        internal const string GeneratedProgramClassPrefix = "FlowProgram_";
        internal const string GeneratedSourceExtension = ".generated.cs";

        internal static readonly string[] ProgramUsingLines =
        {
            "using System.Threading;",
            "using Ceres.Graph;",
            "using Ceres.Graph.Flow;",
            "using Ceres.Graph.Flow.Utilities;",
            "using Chris.Resource;",
            "using Chris.Events;",
            "using Cysharp.Threading.Tasks;",
            "using R3;",
            "using R3.Chris;",
            "using UnityEngine;",
            "using UnityEngine.Pool;",
            "using UObject = UnityEngine.Object;"
        };

        internal static readonly string[] GeneratedHeaderLines =
        {
            "/// <auto-generated>",
            "/// This file is auto-generated by Ceres.FlowCSharpRuntimeGenerator. ",
            "/// All changes will be discarded.",
            "/// </auto-generated>"
        };

        [MenuItem(GenerateRuntimeMenuPath + "/Selected Assets", false, 100)]
        private static void GenerateSelected()
        {
            var assets = Selection.objects.OfType<FlowGraphScriptableObjectBase>().Distinct().ToArray();
            if (assets.Length == 0)
            {
                EditorUtility.DisplayDialog("Ceres", "Select one or more FlowGraph assets first.", "OK");
                return;
            }

            GenerateAssets(assets);
        }

        [MenuItem(GenerateRuntimeMenuPath + "/Selected Objects", false, 102)]
        private static void GenerateSelectedObjects()
        {
            var containers = FlowCSharpRuntimeGenerationDriver.FindSelectedManualGeneratedRuntimeContainers().ToArray();
            if (containers.Length == 0)
            {
                EditorUtility.DisplayDialog("Ceres",
                    "Select one or more GenerateFlow components or GameObjects first.", "OK");
                return;
            }

            GenerateManualContainers(containers);
        }

        [MenuItem(GenerateRuntimeMenuPath + "/All Enabled Assets", false, 101)]
        public static void GenerateAllEnabledAssets()
        {
            FlowCSharpRuntimeGenerationDriver.GenerateAllEnabledAssets();
        }

        public static void GenerateAssets(IEnumerable<FlowGraphScriptableObjectBase> assets)
        {
            FlowCSharpRuntimeGenerationDriver.GenerateAssets(assets);
        }

        public static void GenerateAsset(FlowGraphScriptableObjectBase asset)
        {
            FlowCSharpRuntimeGenerationDriver.GenerateAsset(asset);
        }

        public static void GenerateContainer(IFlowGeneratedRuntimeContainer container)
        {
            FlowCSharpRuntimeGenerationDriver.GenerateContainer(container);
        }

        public static void GenerateManualContainer(IFlowGeneratedRuntimeContainer container)
        {
            FlowCSharpRuntimeGenerationDriver.GenerateManualContainer(container);
        }

        public static void GenerateManualContainers(IEnumerable<IFlowGeneratedRuntimeContainer> containers)
        {
            FlowCSharpRuntimeGenerationDriver.GenerateManualContainers(containers);
        }

        public static void SynchronizeManualGeneratedRuntime(IFlowGeneratedRuntimeContainer container)
        {
            FlowCSharpRuntimeGenerationDriver.SynchronizeManualGeneratedRuntime(container);
        }

        public static void ValidateGeneratedAsset(FlowGraphScriptableObjectBase asset)
        {
            FlowCSharpRuntimeGenerationDriver.ValidateGeneratedAsset(asset);
        }

        public static void ValidateGeneratedManifestEntries()
        {
            FlowCSharpRuntimeGenerationDriver.ValidateGeneratedManifestEntries();
        }

        internal static GeneratedSource GenerateSource(string displayName, FlowGraphData graphData,
            string className)
        {
            using var graph = graphData.CreateFlowGraphInstance();
            graph.AOT();
            var compiler = new FlowCSharpCompiler(new FlowCompilationContext(graph, displayName, className,
                FlowCSharpCompilationOptions.Current()));
            var generated = compiler.Compile();
            return new GeneratedSource(generated.Source, generated.FunctionDependencies);
        }

        internal static FlowGeneratedFunctionDependencyInfo[] ValidateSupport(string displayName,
            FlowGraphData graphData)
        {
            using var graph = graphData.CreateFlowGraphInstance();
            graph.AOT();
            var compiler = new FlowCSharpCompiler(new FlowCompilationContext(graph, displayName, "Validation",
                FlowCSharpCompilationOptions.Current()));
            return compiler.ValidateSupport();
        }

        internal static string GetFriendlyTypeName(Type type)
        {
            return SourceContext.GetFriendlyTypeName(type);
        }

        internal static string Escape(string value)
        {
            return value?
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n") ?? string.Empty;
        }

        internal static bool TryBuildLiteralExpression(object value, Type expectedType, out string expression)
        {
            expression = null;
            if (expectedType == null)
            {
                return false;
            }

            if (IsNullLiteralValue(value))
            {
                expression = ToNullLiteral(expectedType);
                return true;
            }

            if (expectedType.IsEnum)
            {
                expression =
                    $"({GetFriendlyTypeName(expectedType)}){Convert.ToInt64(value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture)}";
                return true;
            }

            if (expectedType == typeof(string))
            {
                expression = $"\"{Escape(value.ToString())}\"";
                return true;
            }

            if (expectedType == typeof(bool))
            {
                expression = value is bool boolValue && boolValue ? "true" : "false";
                return true;
            }

            if (expectedType == typeof(int))
            {
                expression = value is int intValue ? intValue.ToString(CultureInfo.InvariantCulture) : "0";
                return true;
            }

            if (expectedType == typeof(float))
            {
                expression = value is float floatValue ? floatValue.ToString(CultureInfo.InvariantCulture) + "f" : "0f";
                return true;
            }

            if (expectedType == typeof(double))
            {
                expression = value is double doubleValue ? doubleValue.ToString(CultureInfo.InvariantCulture) : "0d";
                return true;
            }

            if (expectedType == typeof(long))
            {
                expression = value is long longValue ? longValue.ToString(CultureInfo.InvariantCulture) + "L" : "0L";
                return true;
            }

            if (expectedType == typeof(short))
            {
                expression = value is short shortValue
                    ? $"(short){shortValue.ToString(CultureInfo.InvariantCulture)}"
                    : "default(short)";
                return true;
            }

            if (expectedType == typeof(byte))
            {
                expression = value is byte byteValue
                    ? $"(byte){byteValue.ToString(CultureInfo.InvariantCulture)}"
                    : "default(byte)";
                return true;
            }

            if (expectedType == typeof(Vector2) && value is Vector2 vector2)
            {
                expression =
                    $"new Vector2({vector2.x.ToString(CultureInfo.InvariantCulture)}f, {vector2.y.ToString(CultureInfo.InvariantCulture)}f)";
                return true;
            }

            if (expectedType == typeof(Vector3) && value is Vector3 vector3)
            {
                expression =
                    $"new Vector3({vector3.x.ToString(CultureInfo.InvariantCulture)}f, {vector3.y.ToString(CultureInfo.InvariantCulture)}f, {vector3.z.ToString(CultureInfo.InvariantCulture)}f)";
                return true;
            }

            if (expectedType == typeof(Quaternion) && value is Quaternion quaternion)
            {
                expression =
                    $"new Quaternion({quaternion.x.ToString(CultureInfo.InvariantCulture)}f, {quaternion.y.ToString(CultureInfo.InvariantCulture)}f, {quaternion.z.ToString(CultureInfo.InvariantCulture)}f, {quaternion.w.ToString(CultureInfo.InvariantCulture)}f)";
                return true;
            }

            if (expectedType != typeof(object))
            {
                return false;
            }

            switch (value)
            {
                case string text:
                    expression = $"\"{Escape(text)}\"";
                    return true;
                case bool objectBool:
                    expression = objectBool ? "true" : "false";
                    return true;
                case int objectInt:
                    expression = objectInt.ToString(CultureInfo.InvariantCulture);
                    return true;
                case float objectFloat:
                    expression = objectFloat.ToString(CultureInfo.InvariantCulture) + "f";
                    return true;
                case double objectDouble:
                    expression = objectDouble.ToString(CultureInfo.InvariantCulture);
                    return true;
                case long objectLong:
                    expression = objectLong.ToString(CultureInfo.InvariantCulture) + "L";
                    return true;
                default:
                    return false;
            }
        }

        internal static bool IsNullLiteralValue(object value)
        {
            return value == null || value is UObject unityObject && !unityObject;
        }

        internal static string ToNullLiteral(Type expectedType)
        {
            return expectedType.IsValueType && Nullable.GetUnderlyingType(expectedType) == null
                ? $"default({GetFriendlyTypeName(expectedType)})"
                : "null";
        }

        internal static void AppendGeneratedPreamble(StringBuilder body, IEnumerable<string> usingLines)
        {
            AppendLines(body, GeneratedHeaderLines);
            AppendLines(body, usingLines);
            body.AppendLine();
        }

        private static void AppendLines(StringBuilder body, IEnumerable<string> lines)
        {
            foreach (var line in lines)
            {
                body.AppendLine(line);
            }
        }

        internal readonly struct GeneratedSource
        {
            public readonly string Source;

            public readonly FlowGeneratedFunctionDependencyInfo[] FunctionDependencies;

            public GeneratedSource(string source, FlowGeneratedFunctionDependencyInfo[] functionDependencies)
            {
                Source = source;
                FunctionDependencies = functionDependencies;
            }
        }

        internal static string SanitizeIdentifier(string value)
        {
            if (string.IsNullOrEmpty(value)) return "Unnamed";
            var builder = new StringBuilder(value.Length);
            foreach (var c in value)
            {
                builder.Append(char.IsLetterOrDigit(c) ? c : '_');
            }

            if (builder.Length == 0 || char.IsDigit(builder[0]))
            {
                builder.Insert(0, '_');
            }

            return builder.ToString();
        }

        internal static bool CanDirectCall(FlowNode_ExecuteFunction node, out DirectCallInfo directCall)
        {
            directCall = default;

            if (!TryGetMethodCallInfo(node, out var methodInfo, out var targetType, out var declaringType,
                    out var parameterTypes))
            {
                return false;
            }

            if (!methodInfo.IsPublic || !IsVisibleType(declaringType))
            {
                return false;
            }

            directCall = new DirectCallInfo(declaringType, targetType, methodInfo, methodInfo.ReturnType,
                parameterTypes, false);
            return true;
        }

        internal static bool CanGeneratedCall(FlowNode_ExecuteFunction node, out DirectCallInfo directCall)
        {
            if (CanDirectCall(node, out directCall))
            {
                return true;
            }

            if (!TryGetMethodCallInfo(node, out var methodInfo, out var targetType, out var declaringType,
                    out var parameterTypes))
            {
                return false;
            }

            directCall = new DirectCallInfo(declaringType, targetType, methodInfo, methodInfo.ReturnType,
                parameterTypes, true);
            return true;
        }

        private static bool TryGetMethodCallInfo(FlowNode_ExecuteFunction node, out MethodInfo methodInfo,
            out Type targetType, out Type declaringType, out Type[] parameterTypes)
        {
            methodInfo = null;
            targetType = null;
            declaringType = null;
            parameterTypes = null;

            targetType = GetTargetType(node);
            if (targetType == null || !IsVisibleType(targetType))
            {
                return false;
            }

            try
            {
                methodInfo = node.GetMethodInfo(targetType);
            }
            catch
            {
                return false;
            }

            if (methodInfo == null ||
                methodInfo.IsStatic != node.isStatic ||
                methodInfo.ContainsGenericParameters ||
                methodInfo.IsGenericMethodDefinition ||
                !IsVisibleType(methodInfo.ReturnType))
            {
                return false;
            }

            declaringType = methodInfo.DeclaringType ?? targetType;

            var parameters = methodInfo.GetParameters();
            if (parameters.Length > 6)
            {
                return false;
            }

            parameterTypes = new Type[parameters.Length];
            for (var i = 0; i < parameters.Length; i++)
            {
                var parameterType = parameters[i].ParameterType;
                if (parameterType.IsByRef ||
                    parameterType.IsPointer ||
                    parameterType.IsGenericParameter ||
                    !IsVisibleType(parameterType))
                {
                    return false;
                }

                parameterTypes[i] = parameterType;
            }

            return true;
        }

        internal static bool CanDirectGetProperty(PropertyNode_PropertyValue node, out PropertyCallInfo propertyCall)
        {
            return CanDirectProperty(node, true, out propertyCall);
        }

        internal static bool CanDirectSetProperty(PropertyNode_PropertyValue node, out PropertyCallInfo propertyCall)
        {
            return CanDirectProperty(node, false, out propertyCall);
        }

        private static bool CanDirectProperty(PropertyNode_PropertyValue node, bool getter,
            out PropertyCallInfo propertyCall)
        {
            propertyCall = default;

            var targetType = GetPropertyTargetType(node);
            if (targetType == null || !IsVisibleType(targetType))
            {
                return false;
            }

            var propertyInfo = node.GetPropertyInfo(targetType);
            if (propertyInfo == null ||
                !IsVisibleType(propertyInfo.PropertyType))
            {
                return false;
            }

            var accessor = getter ? propertyInfo.GetGetMethod(false) : propertyInfo.GetSetMethod(false);
            if (accessor == null || !accessor.IsPublic || accessor.IsStatic != node.isStatic)
            {
                return false;
            }

            var declaringType = propertyInfo.DeclaringType ?? targetType;
            if (!IsVisibleType(declaringType))
            {
                return false;
            }

            propertyCall = new PropertyCallInfo(declaringType, targetType, propertyInfo.Name,
                propertyInfo.PropertyType);
            return true;
        }

        internal static bool CanAccessSharedVariable(PropertyNode_SharedVariableValue node, out Type variableType,
            out Type valueType)
        {
            return CanAccessSharedVariable(node, out variableType, out _, out valueType);
        }

        internal static bool CanAccessSharedVariable(PropertyNode_SharedVariableValue node, out Type variableType,
            out Type variableValueType, out Type portValueType)
        {
            variableType = null;
            variableValueType = null;
            portValueType = null;

            var arguments = GetGenericArguments(node);
            if (arguments.Length < 3)
            {
                return false;
            }

            variableType = arguments[0];
            variableValueType = arguments[1];
            portValueType = arguments[2];
            return IsVisibleType(variableType) &&
                   IsVisibleType(variableValueType) &&
                   IsVisibleType(portValueType);
        }

        private static Type GetTargetType(FlowNode_ExecuteFunction node)
        {
            var arguments = GetGenericArguments(node);
            return arguments.Length > 0 ? arguments[0] : null;
        }

        private static Type GetPropertyTargetType(PropertyNode_PropertyValue node)
        {
            var arguments = GetGenericArguments(node);
            return arguments.Length > 0 ? arguments[0] : null;
        }

        internal static bool TryGetSelfReferenceTargetType(PropertyNode node, out Type targetType)
        {
            targetType = null;
            if (!IsGenericInstance(node, typeof(PropertyNode_GetSelfTReference<>)))
            {
                return false;
            }

            var portType = node.NodeData?.FindPortData("outputValue")?.GetValueType();
            if (portType != null &&
                typeof(UObject).IsAssignableFrom(portType) &&
                IsVisibleType(portType))
            {
                targetType = portType;
                return true;
            }

            var arguments = GetGenericArguments(node);
            if (arguments.Length == 0 ||
                !typeof(UObject).IsAssignableFrom(arguments[0]) ||
                !IsVisibleType(arguments[0]))
            {
                return false;
            }

            targetType = arguments[0];
            return true;
        }

        internal static Type[] GetGenericArguments(object value)
        {
            var type = value.GetType();
            while (type != null)
            {
                if (type.IsGenericType)
                {
                    return type.GetGenericArguments();
                }

                type = type.BaseType;
            }

            return Type.EmptyTypes;
        }

        internal static bool TryGetCustomExecutionEventBaseType(ExecutableEvent evt, out Type eventBaseType)
        {
            eventBaseType = null;
            var type = evt?.GetType();
            while (type != null)
            {
                if (type.IsGenericType &&
                    type.GetGenericTypeDefinition() == typeof(CustomExecutionEvent<>))
                {
                    eventBaseType = type.GetGenericArguments()[0];
                    return IsVisibleType(eventBaseType);
                }

                type = type.BaseType;
            }

            return false;
        }

        internal static bool IsGenericInstance(object value, Type genericTypeDefinition)
        {
            var type = value.GetType();
            while (type != null)
            {
                if (type.IsGenericType && type.GetGenericTypeDefinition() == genericTypeDefinition)
                {
                    return true;
                }

                type = type.BaseType;
            }

            return false;
        }

        internal static bool IsVisibleType(Type type)
        {
            if (type == null) return false;
            if (type.IsByRef || type.IsPointer || type.IsGenericParameter) return false;
            if (type.IsArray) return IsVisibleType(type.GetElementType());
            if (!IsVisibleTypeDefinition(type)) return false;

            return !type.IsGenericType || type.GetGenericArguments().All(IsVisibleType);
        }

        private static bool IsVisibleTypeDefinition(Type type)
        {
            if (!type.IsNested)
            {
                return type.IsPublic;
            }

            while (type != null && type.IsNested)
            {
                if (!type.IsNestedPublic)
                {
                    return false;
                }

                type = type.DeclaringType;
            }

            return type == null || type.IsPublic;
        }

        internal readonly struct DirectCallInfo
        {
            public readonly Type DeclaringType;

            public readonly Type TargetType;

            public readonly MethodInfo MethodInfo;

            public readonly string MethodName;

            public readonly Type ReturnType;

            public readonly Type[] ParameterTypes;

            public readonly bool UseInvoker;

            public DirectCallInfo(Type declaringType, Type targetType, MethodInfo methodInfo, Type returnType,
                Type[] parameterTypes, bool useInvoker)
            {
                DeclaringType = declaringType;
                TargetType = targetType;
                MethodInfo = methodInfo;
                MethodName = methodInfo.Name;
                ReturnType = returnType;
                ParameterTypes = parameterTypes;
                UseInvoker = useInvoker;
            }
        }

        internal readonly struct PropertyCallInfo
        {
            public readonly Type DeclaringType;

            public readonly Type TargetType;

            public readonly string PropertyName;

            public readonly Type PropertyType;

            public PropertyCallInfo(Type declaringType, Type targetType, string propertyName, Type propertyType)
            {
                DeclaringType = declaringType;
                TargetType = targetType;
                PropertyName = propertyName;
                PropertyType = propertyType;
            }
        }

    }

    internal sealed class FlowGeneratedRuntimeBuildValidator : IPreprocessBuildWithReport
    {
        public int callbackOrder => 0;

        public void OnPreprocessBuild(BuildReport report)
        {
            foreach (var asset in AssetDatabase.FindAssets($"t:{nameof(FlowGraphScriptableObjectBase)}")
                         .Select(AssetDatabase.GUIDToAssetPath)
                         .Select(AssetDatabase.LoadAssetAtPath<FlowGraphScriptableObjectBase>)
                         .Where(asset => asset && asset.generatedRuntimeInfo.enabled))
            {
                FlowCSharpRuntimeGenerator.ValidateGeneratedAsset(asset);
            }

            FlowCSharpRuntimeGenerator.ValidateGeneratedManifestEntries();
        }
    }
}
