### YamlMime:ManagedReference
items:
- uid: Ceres.Editor.FlowSettings
  commentId: T:Ceres.Editor.FlowSettings
  id: FlowSettings
  parent: Ceres.Editor
  children:
  - Ceres.Editor.FlowSettings.SaveSettings
  langs:
  - csharp
  - vb
  name: FlowSettings
  nameWithType: FlowSettings
  fullName: Ceres.Editor.FlowSettings
  type: Class
  source:
    id: FlowSettings
    path: ''
    startLine: 7661
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Editor
  syntax:
    content: 'public class FlowSettings : ConfigSingleton<FlowSettings>'
    content.vb: Public Class FlowSettings Inherits ConfigSingleton(Of FlowSettings)
  inheritance:
  - System.Object
- uid: Ceres.Editor.FlowSettings.SaveSettings
  commentId: M:Ceres.Editor.FlowSettings.SaveSettings
  id: SaveSettings
  parent: Ceres.Editor.FlowSettings
  langs:
  - csharp
  - vb
  name: SaveSettings()
  nameWithType: FlowSettings.SaveSettings()
  fullName: Ceres.Editor.FlowSettings.SaveSettings()
  type: Method
  source:
    id: SaveSettings
    path: ''
    startLine: 7672
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Editor
  syntax:
    content: public static void SaveSettings()
    content.vb: Public Shared Sub SaveSettings()
  overload: Ceres.Editor.FlowSettings.SaveSettings*
references:
- uid: Ceres.Editor
  commentId: N:Ceres.Editor
  name: Ceres.Editor
  nameWithType: Ceres.Editor
  fullName: Ceres.Editor
  spec.csharp:
  - uid: Ceres
    name: Ceres
  - name: .
  - uid: Ceres.Editor
    name: Editor
  spec.vb:
  - uid: Ceres
    name: Ceres
  - name: .
  - uid: Ceres.Editor
    name: Editor
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Ceres.Editor.FlowSettings.SaveSettings*
  commentId: Overload:Ceres.Editor.FlowSettings.SaveSettings
  name: SaveSettings
  nameWithType: FlowSettings.SaveSettings
  fullName: Ceres.Editor.FlowSettings.SaveSettings
