### YamlMime:ManagedReference
items:
- uid: Ceres.CeresConfig
  commentId: T:Ceres.CeresConfig
  id: CeresConfig
  parent: Ceres
  children: []
  langs:
  - csharp
  - vb
  name: CeresConfig
  nameWithType: CeresConfig
  fullName: Ceres.CeresConfig
  type: Class
  source:
    id: CeresConfig
    path: ''
    startLine: 16868
  assemblies:
  - cs.temp.dll
  namespace: Ceres
  syntax:
    content: 'public class CeresConfig : Config<CeresConfig>'
    content.vb: Public Class CeresConfig Inherits Config(Of CeresConfig)
  inheritance:
  - System.Object
references:
- uid: Ceres
  commentId: N:Ceres
  name: Ceres
  nameWithType: Ceres
  fullName: Ceres
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
