### YamlMime:ManagedReference
items:
- uid: Ceres.Graph.Flow.Utilities.FlowNode_SwitchString.Settings
  commentId: T:Ceres.Graph.Flow.Utilities.FlowNode_SwitchString.Settings
  id: FlowNode_SwitchString.Settings
  parent: Ceres.Graph.Flow.Utilities
  children:
  - Ceres.Graph.Flow.Utilities.FlowNode_SwitchString.Settings.conditions
  - Ceres.Graph.Flow.Utilities.FlowNode_SwitchString.Settings.hasDefault
  langs:
  - csharp
  - vb
  name: FlowNode_SwitchString.Settings
  nameWithType: FlowNode_SwitchString.Settings
  fullName: Ceres.Graph.Flow.Utilities.FlowNode_SwitchString.Settings
  type: Struct
  source:
    id: Settings
    path: ''
    startLine: 28667
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Graph.Flow.Utilities
  syntax:
    content: public struct FlowNode_SwitchString.Settings
    content.vb: Public Structure FlowNode_SwitchString.Settings
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: Ceres.Graph.Flow.Utilities.FlowNode_SwitchString.Settings.conditions
  commentId: F:Ceres.Graph.Flow.Utilities.FlowNode_SwitchString.Settings.conditions
  id: conditions
  parent: Ceres.Graph.Flow.Utilities.FlowNode_SwitchString.Settings
  langs:
  - csharp
  - vb
  name: conditions
  nameWithType: FlowNode_SwitchString.Settings.conditions
  fullName: Ceres.Graph.Flow.Utilities.FlowNode_SwitchString.Settings.conditions
  type: Field
  source:
    id: conditions
    path: ''
    startLine: 28670
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Graph.Flow.Utilities
  syntax:
    content: public string[] conditions
    return:
      type: System.String[]
    content.vb: Public conditions As String()
- uid: Ceres.Graph.Flow.Utilities.FlowNode_SwitchString.Settings.hasDefault
  commentId: F:Ceres.Graph.Flow.Utilities.FlowNode_SwitchString.Settings.hasDefault
  id: hasDefault
  parent: Ceres.Graph.Flow.Utilities.FlowNode_SwitchString.Settings
  langs:
  - csharp
  - vb
  name: hasDefault
  nameWithType: FlowNode_SwitchString.Settings.hasDefault
  fullName: Ceres.Graph.Flow.Utilities.FlowNode_SwitchString.Settings.hasDefault
  type: Field
  source:
    id: hasDefault
    path: ''
    startLine: 28672
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Graph.Flow.Utilities
  syntax:
    content: public bool hasDefault
    return:
      type: System.Boolean
    content.vb: Public hasDefault As Boolean
references:
- uid: Ceres.Graph.Flow.Utilities
  commentId: N:Ceres.Graph.Flow.Utilities
  name: Ceres.Graph.Flow.Utilities
  nameWithType: Ceres.Graph.Flow.Utilities
  fullName: Ceres.Graph.Flow.Utilities
  spec.csharp:
  - uid: Ceres
    name: Ceres
  - name: .
  - uid: Ceres.Graph
    name: Graph
  - name: .
  - uid: Ceres.Graph.Flow
    name: Flow
  - name: .
  - uid: Ceres.Graph.Flow.Utilities
    name: Utilities
  spec.vb:
  - uid: Ceres
    name: Ceres
  - name: .
  - uid: Ceres.Graph
    name: Graph
  - name: .
  - uid: Ceres.Graph.Flow
    name: Flow
  - name: .
  - uid: Ceres.Graph.Flow.Utilities
    name: Utilities
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String[]
  isExternal: true
  name: string[]
  nameWithType: string[]
  fullName: string[]
  nameWithType.vb: String()
  fullName.vb: String()
  name.vb: String()
  spec.csharp:
  - uid: System.String
    name: string
    isExternal: true
  - name: '['
  - name: ']'
  spec.vb:
  - uid: System.String
    name: String
    isExternal: true
  - name: (
  - name: )
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
