### YamlMime:ManagedReference
items:
- uid: Ceres.Editor.CeresSettings.GraphEditorDisplayMode
  commentId: T:Ceres.Editor.CeresSettings.GraphEditorDisplayMode
  id: CeresSettings.GraphEditorDisplayMode
  parent: Ceres.Editor
  children:
  - Ceres.Editor.CeresSettings.GraphEditorDisplayMode.Debug
  - Ceres.Editor.CeresSettings.GraphEditorDisplayMode.Normal
  langs:
  - csharp
  - vb
  name: CeresSettings.GraphEditorDisplayMode
  nameWithType: CeresSettings.GraphEditorDisplayMode
  fullName: Ceres.Editor.CeresSettings.GraphEditorDisplayMode
  type: Enum
  source:
    id: GraphEditorDisplayMode
    path: ''
    startLine: 576
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Editor
  syntax:
    content: public enum CeresSettings.GraphEditorDisplayMode
    content.vb: Public Enum CeresSettings.GraphEditorDisplayMode
- uid: Ceres.Editor.CeresSettings.GraphEditorDisplayMode.Normal
  commentId: F:Ceres.Editor.CeresSettings.GraphEditorDisplayMode.Normal
  id: Normal
  parent: Ceres.Editor.CeresSettings.GraphEditorDisplayMode
  langs:
  - csharp
  - vb
  name: Normal
  nameWithType: CeresSettings.GraphEditorDisplayMode.Normal
  fullName: Ceres.Editor.CeresSettings.GraphEditorDisplayMode.Normal
  type: Field
  source:
    id: Normal
    path: ''
    startLine: 578
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Editor
  syntax:
    content: Normal = 0
    return:
      type: Ceres.Editor.CeresSettings.GraphEditorDisplayMode
- uid: Ceres.Editor.CeresSettings.GraphEditorDisplayMode.Debug
  commentId: F:Ceres.Editor.CeresSettings.GraphEditorDisplayMode.Debug
  id: Debug
  parent: Ceres.Editor.CeresSettings.GraphEditorDisplayMode
  langs:
  - csharp
  - vb
  name: Debug
  nameWithType: CeresSettings.GraphEditorDisplayMode.Debug
  fullName: Ceres.Editor.CeresSettings.GraphEditorDisplayMode.Debug
  type: Field
  source:
    id: Debug
    path: ''
    startLine: 579
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Editor
  syntax:
    content: Debug = 1
    return:
      type: Ceres.Editor.CeresSettings.GraphEditorDisplayMode
references:
- uid: Ceres.Editor
  commentId: N:Ceres.Editor
  name: Ceres.Editor
  nameWithType: Ceres.Editor
  fullName: Ceres.Editor
  spec.csharp:
  - uid: Ceres
    name: Ceres
  - name: .
  - uid: Ceres.Editor
    name: Editor
  spec.vb:
  - uid: Ceres
    name: Ceres
  - name: .
  - uid: Ceres.Editor
    name: Editor
- uid: Ceres.Editor.CeresSettings.GraphEditorDisplayMode
  commentId: T:Ceres.Editor.CeresSettings.GraphEditorDisplayMode
  parent: Ceres.Editor
  name: CeresSettings.GraphEditorDisplayMode
  nameWithType: CeresSettings.GraphEditorDisplayMode
  fullName: Ceres.Editor.CeresSettings.GraphEditorDisplayMode
  spec.csharp:
  - uid: Ceres.Editor.CeresSettings
    name: CeresSettings
  - name: .
  - uid: Ceres.Editor.CeresSettings.GraphEditorDisplayMode
    name: GraphEditorDisplayMode
  spec.vb:
  - uid: Ceres.Editor.CeresSettings
    name: CeresSettings
  - name: .
  - uid: Ceres.Editor.CeresSettings.GraphEditorDisplayMode
    name: GraphEditorDisplayMode
