### YamlMime:ManagedReference
items:
- uid: Ceres.Editor.Graph.NodeSettingsElement
  commentId: T:Ceres.Editor.Graph.NodeSettingsElement
  id: NodeSettingsElement
  parent: Ceres.Editor.Graph
  children:
  - Ceres.Editor.Graph.NodeSettingsElement.#ctor
  - Ceres.Editor.Graph.NodeSettingsElement.contentContainer
  - Ceres.Editor.Graph.NodeSettingsElement.Label
  langs:
  - csharp
  - vb
  name: NodeSettingsElement
  nameWithType: NodeSettingsElement
  fullName: Ceres.Editor.Graph.NodeSettingsElement
  type: Class
  source:
    id: NodeSettingsElement
    path: ''
    startLine: 5132
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Editor.Graph
  syntax:
    content: 'public class NodeSettingsElement : VisualElement'
    content.vb: Public Class NodeSettingsElement Inherits VisualElement
  inheritance:
  - System.Object
- uid: Ceres.Editor.Graph.NodeSettingsElement.Label
  commentId: P:Ceres.Editor.Graph.NodeSettingsElement.Label
  id: Label
  parent: Ceres.Editor.Graph.NodeSettingsElement
  langs:
  - csharp
  - vb
  name: Label
  nameWithType: NodeSettingsElement.Label
  fullName: Ceres.Editor.Graph.NodeSettingsElement.Label
  type: Property
  source:
    id: Label
    path: ''
    startLine: 5136
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Editor.Graph
  syntax:
    content: public Label Label { get; }
    parameters: []
    return:
      type: Global.Label
    content.vb: Public ReadOnly Property Label As Label
  overload: Ceres.Editor.Graph.NodeSettingsElement.Label*
- uid: Ceres.Editor.Graph.NodeSettingsElement.#ctor
  commentId: M:Ceres.Editor.Graph.NodeSettingsElement.#ctor
  id: '#ctor'
  parent: Ceres.Editor.Graph.NodeSettingsElement
  langs:
  - csharp
  - vb
  name: NodeSettingsElement()
  nameWithType: NodeSettingsElement.NodeSettingsElement()
  fullName: Ceres.Editor.Graph.NodeSettingsElement.NodeSettingsElement()
  type: Constructor
  source:
    id: .ctor
    path: ''
    startLine: 5138
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Editor.Graph
  syntax:
    content: public NodeSettingsElement()
    content.vb: Public Sub New()
  overload: Ceres.Editor.Graph.NodeSettingsElement.#ctor*
  nameWithType.vb: NodeSettingsElement.New()
  fullName.vb: Ceres.Editor.Graph.NodeSettingsElement.New()
  name.vb: New()
- uid: Ceres.Editor.Graph.NodeSettingsElement.contentContainer
  commentId: P:Ceres.Editor.Graph.NodeSettingsElement.contentContainer
  id: contentContainer
  parent: Ceres.Editor.Graph.NodeSettingsElement
  langs:
  - csharp
  - vb
  name: contentContainer
  nameWithType: NodeSettingsElement.contentContainer
  fullName: Ceres.Editor.Graph.NodeSettingsElement.contentContainer
  type: Property
  source:
    id: contentContainer
    path: ''
    startLine: 5167
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Editor.Graph
  syntax:
    content: public override VisualElement contentContainer { get; }
    parameters: []
    return:
      type: Global.VisualElement
    content.vb: Public Overrides ReadOnly Property contentContainer As VisualElement
  overload: Ceres.Editor.Graph.NodeSettingsElement.contentContainer*
references:
- uid: Ceres.Editor.Graph
  commentId: N:Ceres.Editor.Graph
  name: Ceres.Editor.Graph
  nameWithType: Ceres.Editor.Graph
  fullName: Ceres.Editor.Graph
  spec.csharp:
  - uid: Ceres
    name: Ceres
  - name: .
  - uid: Ceres.Editor
    name: Editor
  - name: .
  - uid: Ceres.Editor.Graph
    name: Graph
  spec.vb:
  - uid: Ceres
    name: Ceres
  - name: .
  - uid: Ceres.Editor
    name: Editor
  - name: .
  - uid: Ceres.Editor.Graph
    name: Graph
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Ceres.Editor.Graph.NodeSettingsElement.Label*
  commentId: Overload:Ceres.Editor.Graph.NodeSettingsElement.Label
  name: Label
  nameWithType: NodeSettingsElement.Label
  fullName: Ceres.Editor.Graph.NodeSettingsElement.Label
- uid: Global.Label
  commentId: '!:Global.Label'
  isExternal: true
  name: Label
  nameWithType: Label
  fullName: Label
- uid: Ceres.Editor.Graph.NodeSettingsElement.#ctor*
  commentId: Overload:Ceres.Editor.Graph.NodeSettingsElement.#ctor
  name: NodeSettingsElement
  nameWithType: NodeSettingsElement.NodeSettingsElement
  fullName: Ceres.Editor.Graph.NodeSettingsElement.NodeSettingsElement
  nameWithType.vb: NodeSettingsElement.New
  fullName.vb: Ceres.Editor.Graph.NodeSettingsElement.New
  name.vb: New
- uid: Ceres.Editor.Graph.NodeSettingsElement.contentContainer*
  commentId: Overload:Ceres.Editor.Graph.NodeSettingsElement.contentContainer
  name: contentContainer
  nameWithType: NodeSettingsElement.contentContainer
  fullName: Ceres.Editor.Graph.NodeSettingsElement.contentContainer
- uid: Global.VisualElement
  isExternal: true
  name: VisualElement
  nameWithType: VisualElement
  fullName: VisualElement
