### YamlMime:ManagedReference
items:
- uid: Ceres.Graph.APIUpdateConfig
  commentId: T:Ceres.Graph.APIUpdateConfig
  id: APIUpdateConfig
  parent: Ceres.Graph
  children:
  - Ceres.Graph.APIUpdateConfig.AutoScope
  - Ceres.Graph.APIUpdateConfig.Current
  - Ceres.Graph.APIUpdateConfig.RedirectManagedReference(Ceres.ManagedReferenceType)
  - Ceres.Graph.APIUpdateConfig.RedirectNode(Ceres.ManagedReferenceType@)
  - Ceres.Graph.APIUpdateConfig.RedirectSerializedType(System.String)
  - Ceres.Graph.APIUpdateConfig.RedirectVariable(Ceres.ManagedReferenceType@)
  langs:
  - csharp
  - vb
  name: APIUpdateConfig
  nameWithType: APIUpdateConfig
  fullName: Ceres.Graph.APIUpdateConfig
  type: Class
  source:
    id: APIUpdateConfig
    path: ''
    startLine: 17811
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Graph
  syntax:
    content: 'public class APIUpdateConfig : ScriptableObject'
    content.vb: Public Class APIUpdateConfig Inherits ScriptableObject
  inheritance:
  - System.Object
- uid: Ceres.Graph.APIUpdateConfig.RedirectNode(Ceres.ManagedReferenceType@)
  commentId: M:Ceres.Graph.APIUpdateConfig.RedirectNode(Ceres.ManagedReferenceType@)
  id: RedirectNode(Ceres.ManagedReferenceType@)
  parent: Ceres.Graph.APIUpdateConfig
  langs:
  - csharp
  - vb
  name: RedirectNode(in ManagedReferenceType)
  nameWithType: APIUpdateConfig.RedirectNode(in ManagedReferenceType)
  fullName: Ceres.Graph.APIUpdateConfig.RedirectNode(in Ceres.ManagedReferenceType)
  type: Method
  source:
    id: RedirectNode
    path: ''
    startLine: 17883
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Graph
  syntax:
    content: public Type RedirectNode(in ManagedReferenceType nodeType)
    parameters:
    - id: nodeType
      type: Ceres.ManagedReferenceType
    return:
      type: Global.Type
    content.vb: Public Function RedirectNode(nodeType As ManagedReferenceType) As Type
  overload: Ceres.Graph.APIUpdateConfig.RedirectNode*
  nameWithType.vb: APIUpdateConfig.RedirectNode(ManagedReferenceType)
  fullName.vb: Ceres.Graph.APIUpdateConfig.RedirectNode(Ceres.ManagedReferenceType)
  name.vb: RedirectNode(ManagedReferenceType)
- uid: Ceres.Graph.APIUpdateConfig.RedirectVariable(Ceres.ManagedReferenceType@)
  commentId: M:Ceres.Graph.APIUpdateConfig.RedirectVariable(Ceres.ManagedReferenceType@)
  id: RedirectVariable(Ceres.ManagedReferenceType@)
  parent: Ceres.Graph.APIUpdateConfig
  langs:
  - csharp
  - vb
  name: RedirectVariable(in ManagedReferenceType)
  nameWithType: APIUpdateConfig.RedirectVariable(in ManagedReferenceType)
  fullName: Ceres.Graph.APIUpdateConfig.RedirectVariable(in Ceres.ManagedReferenceType)
  type: Method
  source:
    id: RedirectVariable
    path: ''
    startLine: 17890
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Graph
  syntax:
    content: public Type RedirectVariable(in ManagedReferenceType variableType)
    parameters:
    - id: variableType
      type: Ceres.ManagedReferenceType
    return:
      type: Global.Type
    content.vb: Public Function RedirectVariable(variableType As ManagedReferenceType) As Type
  overload: Ceres.Graph.APIUpdateConfig.RedirectVariable*
  nameWithType.vb: APIUpdateConfig.RedirectVariable(ManagedReferenceType)
  fullName.vb: Ceres.Graph.APIUpdateConfig.RedirectVariable(Ceres.ManagedReferenceType)
  name.vb: RedirectVariable(ManagedReferenceType)
- uid: Ceres.Graph.APIUpdateConfig.RedirectManagedReference(Ceres.ManagedReferenceType)
  commentId: M:Ceres.Graph.APIUpdateConfig.RedirectManagedReference(Ceres.ManagedReferenceType)
  id: RedirectManagedReference(Ceres.ManagedReferenceType)
  parent: Ceres.Graph.APIUpdateConfig
  langs:
  - csharp
  - vb
  name: RedirectManagedReference(ManagedReferenceType)
  nameWithType: APIUpdateConfig.RedirectManagedReference(ManagedReferenceType)
  fullName: Ceres.Graph.APIUpdateConfig.RedirectManagedReference(Ceres.ManagedReferenceType)
  type: Method
  source:
    id: RedirectManagedReference
    path: ''
    startLine: 17897
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Graph
  syntax:
    content: public Type RedirectManagedReference(ManagedReferenceType managedReferenceType)
    parameters:
    - id: managedReferenceType
      type: Ceres.ManagedReferenceType
    return:
      type: Global.Type
    content.vb: Public Function RedirectManagedReference(managedReferenceType As ManagedReferenceType) As Type
  overload: Ceres.Graph.APIUpdateConfig.RedirectManagedReference*
- uid: Ceres.Graph.APIUpdateConfig.RedirectSerializedType(System.String)
  commentId: M:Ceres.Graph.APIUpdateConfig.RedirectSerializedType(System.String)
  id: RedirectSerializedType(System.String)
  parent: Ceres.Graph.APIUpdateConfig
  langs:
  - csharp
  - vb
  name: RedirectSerializedType(string)
  nameWithType: APIUpdateConfig.RedirectSerializedType(string)
  fullName: Ceres.Graph.APIUpdateConfig.RedirectSerializedType(string)
  type: Method
  source:
    id: RedirectSerializedType
    path: ''
    startLine: 17920
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Graph
  syntax:
    content: public Type RedirectSerializedType(string serializedType)
    parameters:
    - id: serializedType
      type: System.String
    return:
      type: Global.Type
    content.vb: Public Function RedirectSerializedType(serializedType As String) As Type
  overload: Ceres.Graph.APIUpdateConfig.RedirectSerializedType*
  nameWithType.vb: APIUpdateConfig.RedirectSerializedType(String)
  fullName.vb: Ceres.Graph.APIUpdateConfig.RedirectSerializedType(String)
  name.vb: RedirectSerializedType(String)
- uid: Ceres.Graph.APIUpdateConfig.AutoScope
  commentId: M:Ceres.Graph.APIUpdateConfig.AutoScope
  id: AutoScope
  parent: Ceres.Graph.APIUpdateConfig
  langs:
  - csharp
  - vb
  name: AutoScope()
  nameWithType: APIUpdateConfig.AutoScope()
  fullName: Ceres.Graph.APIUpdateConfig.AutoScope()
  type: Method
  source:
    id: AutoScope
    path: ''
    startLine: 17944
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Graph
  syntax:
    content: public static APIUpdateConfig.ConfigAutoScope AutoScope()
    return:
      type: Ceres.Graph.APIUpdateConfig.ConfigAutoScope
    content.vb: Public Shared Function AutoScope() As APIUpdateConfig.ConfigAutoScope
  overload: Ceres.Graph.APIUpdateConfig.AutoScope*
- uid: Ceres.Graph.APIUpdateConfig.Current
  commentId: P:Ceres.Graph.APIUpdateConfig.Current
  id: Current
  parent: Ceres.Graph.APIUpdateConfig
  langs:
  - csharp
  - vb
  name: Current
  nameWithType: APIUpdateConfig.Current
  fullName: Ceres.Graph.APIUpdateConfig.Current
  type: Property
  source:
    id: Current
    path: ''
    startLine: 17959
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Graph
  summary: "\nCurrent active config, can be null if no valid config\n"
  example: []
  syntax:
    content: public static APIUpdateConfig Current { get; }
    parameters: []
    return:
      type: Ceres.Graph.APIUpdateConfig
    content.vb: Public Shared ReadOnly Property Current As APIUpdateConfig
  overload: Ceres.Graph.APIUpdateConfig.Current*
references:
- uid: Ceres.Graph
  commentId: N:Ceres.Graph
  name: Ceres.Graph
  nameWithType: Ceres.Graph
  fullName: Ceres.Graph
  spec.csharp:
  - uid: Ceres
    name: Ceres
  - name: .
  - uid: Ceres.Graph
    name: Graph
  spec.vb:
  - uid: Ceres
    name: Ceres
  - name: .
  - uid: Ceres.Graph
    name: Graph
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Ceres.Graph.APIUpdateConfig.RedirectNode*
  commentId: Overload:Ceres.Graph.APIUpdateConfig.RedirectNode
  name: RedirectNode
  nameWithType: APIUpdateConfig.RedirectNode
  fullName: Ceres.Graph.APIUpdateConfig.RedirectNode
- uid: Ceres.ManagedReferenceType
  commentId: T:Ceres.ManagedReferenceType
  parent: Ceres
  name: ManagedReferenceType
  nameWithType: ManagedReferenceType
  fullName: Ceres.ManagedReferenceType
- uid: Global.Type
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: Type
- uid: Ceres
  commentId: N:Ceres
  name: Ceres
  nameWithType: Ceres
  fullName: Ceres
- uid: Ceres.Graph.APIUpdateConfig.RedirectVariable*
  commentId: Overload:Ceres.Graph.APIUpdateConfig.RedirectVariable
  name: RedirectVariable
  nameWithType: APIUpdateConfig.RedirectVariable
  fullName: Ceres.Graph.APIUpdateConfig.RedirectVariable
- uid: Ceres.Graph.APIUpdateConfig.RedirectManagedReference*
  commentId: Overload:Ceres.Graph.APIUpdateConfig.RedirectManagedReference
  name: RedirectManagedReference
  nameWithType: APIUpdateConfig.RedirectManagedReference
  fullName: Ceres.Graph.APIUpdateConfig.RedirectManagedReference
- uid: Ceres.Graph.APIUpdateConfig.RedirectSerializedType*
  commentId: Overload:Ceres.Graph.APIUpdateConfig.RedirectSerializedType
  name: RedirectSerializedType
  nameWithType: APIUpdateConfig.RedirectSerializedType
  fullName: Ceres.Graph.APIUpdateConfig.RedirectSerializedType
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Ceres.Graph.APIUpdateConfig.AutoScope*
  commentId: Overload:Ceres.Graph.APIUpdateConfig.AutoScope
  name: AutoScope
  nameWithType: APIUpdateConfig.AutoScope
  fullName: Ceres.Graph.APIUpdateConfig.AutoScope
- uid: Ceres.Graph.APIUpdateConfig.ConfigAutoScope
  commentId: T:Ceres.Graph.APIUpdateConfig.ConfigAutoScope
  parent: Ceres.Graph
  name: APIUpdateConfig.ConfigAutoScope
  nameWithType: APIUpdateConfig.ConfigAutoScope
  fullName: Ceres.Graph.APIUpdateConfig.ConfigAutoScope
  spec.csharp:
  - uid: Ceres.Graph.APIUpdateConfig
    name: APIUpdateConfig
  - name: .
  - uid: Ceres.Graph.APIUpdateConfig.ConfigAutoScope
    name: ConfigAutoScope
  spec.vb:
  - uid: Ceres.Graph.APIUpdateConfig
    name: APIUpdateConfig
  - name: .
  - uid: Ceres.Graph.APIUpdateConfig.ConfigAutoScope
    name: ConfigAutoScope
- uid: Ceres.Graph.APIUpdateConfig.Current*
  commentId: Overload:Ceres.Graph.APIUpdateConfig.Current
  name: Current
  nameWithType: APIUpdateConfig.Current
  fullName: Ceres.Graph.APIUpdateConfig.Current
- uid: Ceres.Graph.APIUpdateConfig
  commentId: T:Ceres.Graph.APIUpdateConfig
  parent: Ceres.Graph
  name: APIUpdateConfig
  nameWithType: APIUpdateConfig
  fullName: Ceres.Graph.APIUpdateConfig
