### YamlMime:ManagedReference
items:
- uid: Ceres.Editor.CeresSettings
  commentId: T:Ceres.Editor.CeresSettings
  id: CeresSettings
  parent: Ceres.Editor
  children:
  - Ceres.Editor.CeresSettings.CleanLogAuto
  - Ceres.Editor.CeresSettings.DisplayDebug
  - Ceres.Editor.CeresSettings.DisplayMode
  - Ceres.Editor.CeresSettings.SaveSettings
  langs:
  - csharp
  - vb
  name: CeresSettings
  nameWithType: CeresSettings
  fullName: Ceres.Editor.CeresSettings
  type: Class
  source:
    id: CeresSettings
    path: ''
    startLine: 573
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Editor
  syntax:
    content: 'public class CeresSettings : ConfigSingleton<CeresSettings>'
    content.vb: Public Class CeresSettings Inherits ConfigSingleton(Of CeresSettings)
  inheritance:
  - System.Object
- uid: Ceres.Editor.CeresSettings.CleanLogAuto
  commentId: P:Ceres.Editor.CeresSettings.CleanLogAuto
  id: CleanLogAuto
  parent: Ceres.Editor.CeresSettings
  langs:
  - csharp
  - vb
  name: CleanLogAuto
  nameWithType: CeresSettings.CleanLogAuto
  fullName: Ceres.Editor.CeresSettings.CleanLogAuto
  type: Property
  source:
    id: CleanLogAuto
    path: ''
    startLine: 596
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Editor
  syntax:
    content: public static bool CleanLogAuto { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared ReadOnly Property CleanLogAuto As Boolean
  overload: Ceres.Editor.CeresSettings.CleanLogAuto*
- uid: Ceres.Editor.CeresSettings.DisplayMode
  commentId: P:Ceres.Editor.CeresSettings.DisplayMode
  id: DisplayMode
  parent: Ceres.Editor.CeresSettings
  langs:
  - csharp
  - vb
  name: DisplayMode
  nameWithType: CeresSettings.DisplayMode
  fullName: Ceres.Editor.CeresSettings.DisplayMode
  type: Property
  source:
    id: DisplayMode
    path: ''
    startLine: 601
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Editor
  summary: "\nCeres graph editor view display mode\n"
  example: []
  syntax:
    content: public static CeresSettings.GraphEditorDisplayMode DisplayMode { get; }
    parameters: []
    return:
      type: Ceres.Editor.CeresSettings.GraphEditorDisplayMode
    content.vb: Public Shared ReadOnly Property DisplayMode As CeresSettings.GraphEditorDisplayMode
  overload: Ceres.Editor.CeresSettings.DisplayMode*
- uid: Ceres.Editor.CeresSettings.DisplayDebug
  commentId: P:Ceres.Editor.CeresSettings.DisplayDebug
  id: DisplayDebug
  parent: Ceres.Editor.CeresSettings
  langs:
  - csharp
  - vb
  name: DisplayDebug
  nameWithType: CeresSettings.DisplayDebug
  fullName: Ceres.Editor.CeresSettings.DisplayDebug
  type: Property
  source:
    id: DisplayDebug
    path: ''
    startLine: 606
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Editor
  summary: "\nCeres graph editor will display in debug mode\n"
  example: []
  syntax:
    content: public static bool DisplayDebug { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared ReadOnly Property DisplayDebug As Boolean
  overload: Ceres.Editor.CeresSettings.DisplayDebug*
- uid: Ceres.Editor.CeresSettings.SaveSettings
  commentId: M:Ceres.Editor.CeresSettings.SaveSettings
  id: SaveSettings
  parent: Ceres.Editor.CeresSettings
  langs:
  - csharp
  - vb
  name: SaveSettings()
  nameWithType: CeresSettings.SaveSettings()
  fullName: Ceres.Editor.CeresSettings.SaveSettings()
  type: Method
  source:
    id: SaveSettings
    path: ''
    startLine: 611
  assemblies:
  - cs.temp.dll
  namespace: Ceres.Editor
  summary: "\nSave <xref href=\"Ceres.Editor.CeresSettings\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: public static void SaveSettings()
    content.vb: Public Shared Sub SaveSettings()
  overload: Ceres.Editor.CeresSettings.SaveSettings*
references:
- uid: Ceres.Editor
  commentId: N:Ceres.Editor
  name: Ceres.Editor
  nameWithType: Ceres.Editor
  fullName: Ceres.Editor
  spec.csharp:
  - uid: Ceres
    name: Ceres
  - name: .
  - uid: Ceres.Editor
    name: Editor
  spec.vb:
  - uid: Ceres
    name: Ceres
  - name: .
  - uid: Ceres.Editor
    name: Editor
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Ceres.Editor.CeresSettings.CleanLogAuto*
  commentId: Overload:Ceres.Editor.CeresSettings.CleanLogAuto
  name: CleanLogAuto
  nameWithType: CeresSettings.CleanLogAuto
  fullName: Ceres.Editor.CeresSettings.CleanLogAuto
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Ceres.Editor.CeresSettings.DisplayMode*
  commentId: Overload:Ceres.Editor.CeresSettings.DisplayMode
  name: DisplayMode
  nameWithType: CeresSettings.DisplayMode
  fullName: Ceres.Editor.CeresSettings.DisplayMode
- uid: Ceres.Editor.CeresSettings.GraphEditorDisplayMode
  commentId: T:Ceres.Editor.CeresSettings.GraphEditorDisplayMode
  parent: Ceres.Editor
  name: CeresSettings.GraphEditorDisplayMode
  nameWithType: CeresSettings.GraphEditorDisplayMode
  fullName: Ceres.Editor.CeresSettings.GraphEditorDisplayMode
  spec.csharp:
  - uid: Ceres.Editor.CeresSettings
    name: CeresSettings
  - name: .
  - uid: Ceres.Editor.CeresSettings.GraphEditorDisplayMode
    name: GraphEditorDisplayMode
  spec.vb:
  - uid: Ceres.Editor.CeresSettings
    name: CeresSettings
  - name: .
  - uid: Ceres.Editor.CeresSettings.GraphEditorDisplayMode
    name: GraphEditorDisplayMode
- uid: Ceres.Editor.CeresSettings.DisplayDebug*
  commentId: Overload:Ceres.Editor.CeresSettings.DisplayDebug
  name: DisplayDebug
  nameWithType: CeresSettings.DisplayDebug
  fullName: Ceres.Editor.CeresSettings.DisplayDebug
- uid: Ceres.Editor.CeresSettings
  commentId: T:Ceres.Editor.CeresSettings
  name: CeresSettings
  nameWithType: CeresSettings
  fullName: Ceres.Editor.CeresSettings
- uid: Ceres.Editor.CeresSettings.SaveSettings*
  commentId: Overload:Ceres.Editor.CeresSettings.SaveSettings
  name: SaveSettings
  nameWithType: CeresSettings.SaveSettings
  fullName: Ceres.Editor.CeresSettings.SaveSettings
